/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_nominal_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[11] = {6, 2, 0, 3, 6, 1, 3, 5, 1, 3, 5};
static const casadi_int casadi_s1[15] = {2, 6, 0, 0, 2, 2, 4, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s2[15] = {6, 2, 0, 5, 10, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[17] = {6, 2, 0, 6, 12, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s7[4] = {0, 1, 0, 0};
static const casadi_int casadi_s8[39] = {6, 6, 0, 5, 10, 15, 20, 25, 30, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};

/* quadrotor_nominal_expl_vde_forw:(i0[6],i1[6x6],i2[6x2],i3[2],i4[0])->(o0[6],o1[6x6,30nz],o2[6x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, *w7=w+7, *w8=w+43, *w9=w+49, *w10=w+55, *w11=w+61, *w12=w+67, *w13=w+73, w14, w15, w17, *w18=w+82, *w19=w+85, *w20=w+88, *w21=w+100, *w22=w+112, *w23=w+117, *w24=w+122;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #3: @1 = sin(@0) */
  w1 = sin( w0 );
  /* #4: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #5: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #6: @4 = (@2+@3) */
  w4  = (w2+w3);
  /* #7: @5 = (@1*@4) */
  w5  = (w1*w4);
  /* #8: @6 = 0.0135 */
  w6 = 1.3500000000000000e-02;
  /* #9: @5 = (@5/@6) */
  w5 /= w6;
  /* #10: output[0][1] = @5 */
  if (res[0]) res[0][1] = w5;
  /* #11: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #12: output[0][2] = @5 */
  if (res[0]) res[0][2] = w5;
  /* #13: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #14: @5 = (@0*@4) */
  w5  = (w0*w4);
  /* #15: @5 = (@5/@6) */
  w5 /= w6;
  /* #16: @6 = 9.8 */
  w6 = 9.8000000000000007e+00;
  /* #17: @5 = (@5-@6) */
  w5 -= w6;
  /* #18: output[0][3] = @5 */
  if (res[0]) res[0][3] = w5;
  /* #19: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #20: output[0][4] = @5 */
  if (res[0]) res[0][4] = w5;
  /* #21: @5 = 0.0397 */
  w5 = 3.9699999999999999e-02;
  /* #22: @3 = (@3-@2) */
  w3 -= w2;
  /* #23: @3 = (@5*@3) */
  w3  = (w5*w3);
  /* #24: @2 = 1.4e-05 */
  w2 = 1.4000000000000000e-05;
  /* #25: @3 = (@3/@2) */
  w3 /= w2;
  /* #26: @2 = 1.41421 */
  w2 = 1.4142135623730951e+00;
  /* #27: @3 = (@3/@2) */
  w3 /= w2;
  /* #28: output[0][5] = @3 */
  if (res[0]) res[0][5] = w3;
  /* #29: @7 = input[1][0] */
  casadi_copy(arg[1], 36, w7);
  /* #30: {@8, @9, @10, @11, @12, @13} = horzsplit(@7) */
  casadi_copy(w7, 6, w8);
  casadi_copy(w7+6, 6, w9);
  casadi_copy(w7+12, 6, w10);
  casadi_copy(w7+18, 6, w11);
  casadi_copy(w7+24, 6, w12);
  casadi_copy(w7+30, 6, w13);
  /* #31: {NULL, @3, NULL, @2, @6, @14} = vertsplit(@8) */
  w3 = w8[1];
  w2 = w8[3];
  w6 = w8[4];
  w14 = w8[5];
  /* #32: output[1][0] = @3 */
  if (res[1]) res[1][0] = w3;
  /* #33: @3 = 74.0741 */
  w3 = 7.4074074074074076e+01;
  /* #34: @15 = (@0*@6) */
  w15  = (w0*w6);
  /* #35: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #36: @15 = (@3*@15) */
  w15  = (w3*w15);
  /* #37: output[1][1] = @15 */
  if (res[1]) res[1][1] = w15;
  /* #38: output[1][2] = @2 */
  if (res[1]) res[1][2] = w2;
  /* #39: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #40: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #41: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #42: @6 = (-@6) */
  w6 = (- w6 );
  /* #43: output[1][3] = @6 */
  if (res[1]) res[1][3] = w6;
  /* #44: output[1][4] = @14 */
  if (res[1]) res[1][4] = w14;
  /* #45: {NULL, @14, NULL, @6, @2, @15} = vertsplit(@9) */
  w14 = w9[1];
  w6 = w9[3];
  w2 = w9[4];
  w15 = w9[5];
  /* #46: output[1][5] = @14 */
  if (res[1]) res[1][5] = w14;
  /* #47: @14 = (@0*@2) */
  w14  = (w0*w2);
  /* #48: @14 = (@4*@14) */
  w14  = (w4*w14);
  /* #49: @14 = (@3*@14) */
  w14  = (w3*w14);
  /* #50: output[1][6] = @14 */
  if (res[1]) res[1][6] = w14;
  /* #51: output[1][7] = @6 */
  if (res[1]) res[1][7] = w6;
  /* #52: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #53: @2 = (@4*@2) */
  w2  = (w4*w2);
  /* #54: @2 = (@3*@2) */
  w2  = (w3*w2);
  /* #55: @2 = (-@2) */
  w2 = (- w2 );
  /* #56: output[1][8] = @2 */
  if (res[1]) res[1][8] = w2;
  /* #57: output[1][9] = @15 */
  if (res[1]) res[1][9] = w15;
  /* #58: {NULL, @15, NULL, @2, @6, @14} = vertsplit(@10) */
  w15 = w10[1];
  w2 = w10[3];
  w6 = w10[4];
  w14 = w10[5];
  /* #59: output[1][10] = @15 */
  if (res[1]) res[1][10] = w15;
  /* #60: @15 = (@0*@6) */
  w15  = (w0*w6);
  /* #61: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #62: @15 = (@3*@15) */
  w15  = (w3*w15);
  /* #63: output[1][11] = @15 */
  if (res[1]) res[1][11] = w15;
  /* #64: output[1][12] = @2 */
  if (res[1]) res[1][12] = w2;
  /* #65: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #66: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #67: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #68: @6 = (-@6) */
  w6 = (- w6 );
  /* #69: output[1][13] = @6 */
  if (res[1]) res[1][13] = w6;
  /* #70: output[1][14] = @14 */
  if (res[1]) res[1][14] = w14;
  /* #71: {NULL, @14, NULL, @6, @2, @15} = vertsplit(@11) */
  w14 = w11[1];
  w6 = w11[3];
  w2 = w11[4];
  w15 = w11[5];
  /* #72: output[1][15] = @14 */
  if (res[1]) res[1][15] = w14;
  /* #73: @14 = (@0*@2) */
  w14  = (w0*w2);
  /* #74: @14 = (@4*@14) */
  w14  = (w4*w14);
  /* #75: @14 = (@3*@14) */
  w14  = (w3*w14);
  /* #76: output[1][16] = @14 */
  if (res[1]) res[1][16] = w14;
  /* #77: output[1][17] = @6 */
  if (res[1]) res[1][17] = w6;
  /* #78: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #79: @2 = (@4*@2) */
  w2  = (w4*w2);
  /* #80: @2 = (@3*@2) */
  w2  = (w3*w2);
  /* #81: @2 = (-@2) */
  w2 = (- w2 );
  /* #82: output[1][18] = @2 */
  if (res[1]) res[1][18] = w2;
  /* #83: output[1][19] = @15 */
  if (res[1]) res[1][19] = w15;
  /* #84: {NULL, @15, NULL, @2, @6, @14} = vertsplit(@12) */
  w15 = w12[1];
  w2 = w12[3];
  w6 = w12[4];
  w14 = w12[5];
  /* #85: output[1][20] = @15 */
  if (res[1]) res[1][20] = w15;
  /* #86: @15 = (@0*@6) */
  w15  = (w0*w6);
  /* #87: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #88: @15 = (@3*@15) */
  w15  = (w3*w15);
  /* #89: output[1][21] = @15 */
  if (res[1]) res[1][21] = w15;
  /* #90: output[1][22] = @2 */
  if (res[1]) res[1][22] = w2;
  /* #91: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #92: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #93: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #94: @6 = (-@6) */
  w6 = (- w6 );
  /* #95: output[1][23] = @6 */
  if (res[1]) res[1][23] = w6;
  /* #96: output[1][24] = @14 */
  if (res[1]) res[1][24] = w14;
  /* #97: {NULL, @14, NULL, @6, @2, @15} = vertsplit(@13) */
  w14 = w13[1];
  w6 = w13[3];
  w2 = w13[4];
  w15 = w13[5];
  /* #98: output[1][25] = @14 */
  if (res[1]) res[1][25] = w14;
  /* #99: @14 = (@0*@2) */
  w14  = (w0*w2);
  /* #100: @14 = (@4*@14) */
  w14  = (w4*w14);
  /* #101: @14 = (@3*@14) */
  w14  = (w3*w14);
  /* #102: output[1][26] = @14 */
  if (res[1]) res[1][26] = w14;
  /* #103: output[1][27] = @6 */
  if (res[1]) res[1][27] = w6;
  /* #104: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #105: @2 = (@4*@2) */
  w2  = (w4*w2);
  /* #106: @2 = (@3*@2) */
  w2  = (w3*w2);
  /* #107: @2 = (-@2) */
  w2 = (- w2 );
  /* #108: output[1][28] = @2 */
  if (res[1]) res[1][28] = w2;
  /* #109: output[1][29] = @15 */
  if (res[1]) res[1][29] = w15;
  /* #110: @13 = zeros(2x6,6nz) */
  casadi_clear(w13, 6);
  /* #111: @16 = 00 */
  /* #112: @15 = ones(2x1,1nz) */
  w15 = 1.;
  /* #113: {@2, NULL} = vertsplit(@15) */
  w2 = w15;
  /* #114: @15 = (@1*@2) */
  w15  = (w1*w2);
  /* #115: @15 = (@3*@15) */
  w15  = (w3*w15);
  /* #116: @6 = (@0*@2) */
  w6  = (w0*w2);
  /* #117: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #118: @14 = 0.707107 */
  w14 = 7.0710678118654746e-01;
  /* #119: @17 = 71428.6 */
  w17 = 7.1428571428571435e+04;
  /* #120: @2 = (@5*@2) */
  w2  = (w5*w2);
  /* #121: @2 = (@17*@2) */
  w2  = (w17*w2);
  /* #122: @2 = (@14*@2) */
  w2  = (w14*w2);
  /* #123: @2 = (-@2) */
  w2 = (- w2 );
  /* #124: @18 = vertcat(@16, @15, @16, @6, @16, @2) */
  rr=w18;
  *rr++ = w15;
  *rr++ = w6;
  *rr++ = w2;
  /* #125: @19 = @18[:3] */
  for (rr=w19, ss=w18+0; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #126: (@13[:6:2] = @19) */
  for (rr=w13+0, ss=w19; rr!=w13+6; rr+=2) *rr = *ss++;
  /* #127: @15 = ones(2x1,1nz) */
  w15 = 1.;
  /* #128: {NULL, @6} = vertsplit(@15) */
  w6 = w15;
  /* #129: @15 = (@1*@6) */
  w15  = (w1*w6);
  /* #130: @15 = (@3*@15) */
  w15  = (w3*w15);
  /* #131: @2 = (@0*@6) */
  w2  = (w0*w6);
  /* #132: @2 = (@3*@2) */
  w2  = (w3*w2);
  /* #133: @5 = (@5*@6) */
  w5 *= w6;
  /* #134: @17 = (@17*@5) */
  w17 *= w5;
  /* #135: @14 = (@14*@17) */
  w14 *= w17;
  /* #136: @19 = vertcat(@16, @15, @16, @2, @16, @14) */
  rr=w19;
  *rr++ = w15;
  *rr++ = w2;
  *rr++ = w14;
  /* #137: @18 = @19[:3] */
  for (rr=w18, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #138: (@13[1:7:2] = @18) */
  for (rr=w13+1, ss=w18; rr!=w13+7; rr+=2) *rr = *ss++;
  /* #139: @12 = @13' */
  casadi_trans(w13,casadi_s1, w12, casadi_s0, iw);
  /* #140: @20 = dense(@12) */
  casadi_densify(w12, casadi_s0, w20, 0);
  /* #141: @21 = input[2][0] */
  casadi_copy(arg[2], 12, w21);
  /* #142: {@12, @13} = horzsplit(@21) */
  casadi_copy(w21, 6, w12);
  casadi_copy(w21+6, 6, w13);
  /* #143: {NULL, @15, NULL, @2, @14, @17} = vertsplit(@12) */
  w15 = w12[1];
  w2 = w12[3];
  w14 = w12[4];
  w17 = w12[5];
  /* #144: @5 = (@0*@14) */
  w5  = (w0*w14);
  /* #145: @5 = (@4*@5) */
  w5  = (w4*w5);
  /* #146: @5 = (@3*@5) */
  w5  = (w3*w5);
  /* #147: @14 = (@1*@14) */
  w14  = (w1*w14);
  /* #148: @14 = (@4*@14) */
  w14  = (w4*w14);
  /* #149: @14 = (@3*@14) */
  w14  = (w3*w14);
  /* #150: @14 = (-@14) */
  w14 = (- w14 );
  /* #151: @22 = vertcat(@15, @5, @2, @14, @17, @16) */
  rr=w22;
  *rr++ = w15;
  *rr++ = w5;
  *rr++ = w2;
  *rr++ = w14;
  *rr++ = w17;
  /* #152: {NULL, @15, NULL, @5, @2, @14} = vertsplit(@13) */
  w15 = w13[1];
  w5 = w13[3];
  w2 = w13[4];
  w14 = w13[5];
  /* #153: @0 = (@0*@2) */
  w0 *= w2;
  /* #154: @0 = (@4*@0) */
  w0  = (w4*w0);
  /* #155: @0 = (@3*@0) */
  w0  = (w3*w0);
  /* #156: @1 = (@1*@2) */
  w1 *= w2;
  /* #157: @4 = (@4*@1) */
  w4 *= w1;
  /* #158: @3 = (@3*@4) */
  w3 *= w4;
  /* #159: @3 = (-@3) */
  w3 = (- w3 );
  /* #160: @23 = vertcat(@15, @0, @5, @3, @14, @16) */
  rr=w23;
  *rr++ = w15;
  *rr++ = w0;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w14;
  /* #161: @24 = horzcat(@22, @23) */
  rr=w24;
  for (i=0, cs=w22; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<5; ++i) *rr++ = *cs++;
  /* #162: @21 = dense(@24) */
  casadi_densify(w24, casadi_s2, w21, 0);
  /* #163: @20 = (@20+@21) */
  for (i=0, rr=w20, cs=w21; i<12; ++i) (*rr++) += (*cs++);
  /* #164: output[2][0] = @20 */
  casadi_copy(w20, 12, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nominal_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_nominal_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nominal_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nominal_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_nominal_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nominal_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nominal_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nominal_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nominal_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nominal_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_nominal_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nominal_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nominal_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nominal_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nominal_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s8;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_nominal_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 132;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nominal_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 132*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
