/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cartpole_nominal_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[8] = {5, 1, 0, 4, 1, 2, 3, 4};

/* cartpole_nominal_expl_vde_adj:(i0[4],i1[4],i2,i3[0])->(o0[5x1,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 4, w0);
  /* #1: {@1, @2, @3, @4} = vertsplit(@0) */
  w1 = w0[0];
  w2 = w0[1];
  w3 = w0[2];
  w4 = w0[3];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #4: @5 = sin(@1) */
  w5 = sin( w1 );
  /* #5: @6 = 0.0632813 */
  w6 = 6.3281250000000011e-02;
  /* #6: @7 = 9.8 */
  w7 = 9.8000000000000007e+00;
  /* #7: @8 = (@7*@5) */
  w8  = (w7*w5);
  /* #8: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #9: @9 = input[2][0] */
  w9 = arg[2] ? arg[2][0] : 0;
  /* #10: @10 = input[0][3] */
  w10 = arg[0] ? arg[0][3] : 0;
  /* #11: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #12: @11 = (@6*@11) */
  w11  = (w6*w11);
  /* #13: @12 = (@11*@5) */
  w12  = (w11*w5);
  /* #14: @9 = (@9+@12) */
  w9 += w12;
  /* #15: @12 = 1.2375 */
  w12 = 1.2375000000000000e+00;
  /* #16: @9 = (@9/@12) */
  w9 /= w12;
  /* #17: @13 = (@1*@9) */
  w13  = (w1*w9);
  /* #18: @8 = (@8-@13) */
  w8 -= w13;
  /* #19: @13 = 0.5625 */
  w13 = 5.6250000000000000e-01;
  /* #20: @14 = 1.33333 */
  w14 = 1.3333333333333333e+00;
  /* #21: @15 = 0.1125 */
  w15 = 1.1250000000000002e-01;
  /* #22: @16 = sq(@1) */
  w16 = casadi_sq( w1 );
  /* #23: @16 = (@15*@16) */
  w16  = (w15*w16);
  /* #24: @16 = (@16/@12) */
  w16 /= w12;
  /* #25: @14 = (@14-@16) */
  w14 -= w16;
  /* #26: @14 = (@13*@14) */
  w14  = (w13*w14);
  /* #27: @8 = (@8/@14) */
  w8 /= w14;
  /* #28: @16 = (@6*@8) */
  w16  = (w6*w8);
  /* #29: @12 = 0.808081 */
  w12 = 8.0808080808080807e-01;
  /* #30: @17 = (@12*@2) */
  w17  = (w12*w2);
  /* #31: @16 = (@16*@17) */
  w16 *= w17;
  /* #32: @16 = (@5*@16) */
  w16  = (w5*w16);
  /* #33: @18 = (2.*@1) */
  w18 = (2.* w1 );
  /* #34: @8 = (@8/@14) */
  w8 /= w14;
  /* #35: @17 = (@1*@17) */
  w17  = (w1*w17);
  /* #36: @17 = (@6*@17) */
  w17  = (w6*w17);
  /* #37: @4 = (@4-@17) */
  w4 -= w17;
  /* #38: @8 = (@8*@4) */
  w8 *= w4;
  /* #39: @13 = (@13*@8) */
  w13 *= w8;
  /* #40: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #41: @15 = (@15*@13) */
  w15 *= w13;
  /* #42: @18 = (@18*@15) */
  w18 *= w15;
  /* #43: @18 = (@5*@18) */
  w18  = (w5*w18);
  /* #44: @16 = (@16-@18) */
  w16 -= w18;
  /* #45: @4 = (@4/@14) */
  w4 /= w14;
  /* #46: @9 = (@9*@4) */
  w9 *= w4;
  /* #47: @9 = (@5*@9) */
  w9  = (w5*w9);
  /* #48: @16 = (@16+@9) */
  w16 += w9;
  /* #49: @7 = (@7*@4) */
  w7 *= w4;
  /* #50: @7 = (@1*@7) */
  w7  = (w1*w7);
  /* #51: @16 = (@16+@7) */
  w16 += w7;
  /* #52: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #53: @2 = (@2-@4) */
  w2 -= w4;
  /* #54: @12 = (@12*@2) */
  w12 *= w2;
  /* #55: @11 = (@11*@12) */
  w11 *= w12;
  /* #56: @1 = (@1*@11) */
  w1 *= w11;
  /* #57: @16 = (@16+@1) */
  w16 += w1;
  /* #58: output[0][1] = @16 */
  if (res[0]) res[0][1] = w16;
  /* #59: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #60: @5 = (@5*@12) */
  w5 *= w12;
  /* #61: @6 = (@6*@5) */
  w6 *= w5;
  /* #62: @10 = (@10*@6) */
  w10 *= w6;
  /* #63: @3 = (@3+@10) */
  w3 += w10;
  /* #64: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #65: output[0][3] = @12 */
  if (res[0]) res[0][3] = w12;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cartpole_nominal_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int cartpole_nominal_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cartpole_nominal_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_nominal_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_nominal_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_nominal_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_nominal_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 22;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 22*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
