/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cartpole_nominal_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[6] = {4, 1, 0, 2, 1, 3};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[4] = {0, 1, 0, 0};

/* cartpole_nominal_expl_vde_forw:(i0[4],i1[4x4],i2[4],i3,i4[0])->(o0[4],o1[4x4],o2[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+14, *w15=w+30, *w16=w+34, *w17=w+38, *w18=w+42, w19, w20, w21, w22, w23, w24, *w25=w+52, *w27=w+54, *w28=w+56;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = 0.0632813 */
  w1 = 6.3281250000000011e-02;
  /* #4: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #5: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #6: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #7: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #8: @5 = sin(@4) */
  w5 = sin( w4 );
  /* #9: @6 = (@3*@5) */
  w6  = (w3*w5);
  /* #10: @0 = (@0+@6) */
  w0 += w6;
  /* #11: @6 = 1.2375 */
  w6 = 1.2375000000000000e+00;
  /* #12: @0 = (@0/@6) */
  w0 /= w6;
  /* #13: @7 = 9.8 */
  w7 = 9.8000000000000007e+00;
  /* #14: @8 = (@7*@5) */
  w8  = (w7*w5);
  /* #15: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #16: @9 = (@4*@0) */
  w9  = (w4*w0);
  /* #17: @8 = (@8-@9) */
  w8 -= w9;
  /* #18: @9 = 0.5625 */
  w9 = 5.6250000000000000e-01;
  /* #19: @10 = 1.33333 */
  w10 = 1.3333333333333333e+00;
  /* #20: @11 = 0.1125 */
  w11 = 1.1250000000000002e-01;
  /* #21: @12 = sq(@4) */
  w12 = casadi_sq( w4 );
  /* #22: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #23: @12 = (@12/@6) */
  w12 /= w6;
  /* #24: @10 = (@10-@12) */
  w10 -= w12;
  /* #25: @10 = (@9*@10) */
  w10  = (w9*w10);
  /* #26: @8 = (@8/@10) */
  w8 /= w10;
  /* #27: @12 = (@1*@8) */
  w12  = (w1*w8);
  /* #28: @13 = (@12*@4) */
  w13  = (w12*w4);
  /* #29: @13 = (@13/@6) */
  w13 /= w6;
  /* #30: @13 = (@0-@13) */
  w13  = (w0-w13);
  /* #31: output[0][1] = @13 */
  if (res[0]) res[0][1] = w13;
  /* #32: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #33: output[0][3] = @8 */
  if (res[0]) res[0][3] = w8;
  /* #34: @14 = input[1][0] */
  casadi_copy(arg[1], 16, w14);
  /* #35: {@15, @16, @17, @18} = horzsplit(@14) */
  casadi_copy(w14, 4, w15);
  casadi_copy(w14+4, 4, w16);
  casadi_copy(w14+8, 4, w17);
  casadi_copy(w14+12, 4, w18);
  /* #36: {NULL, @13, @6, @19} = vertsplit(@15) */
  w13 = w15[1];
  w6 = w15[2];
  w19 = w15[3];
  /* #37: output[1][0] = @13 */
  if (res[1]) res[1][0] = w13;
  /* #38: @13 = 0.808081 */
  w13 = 8.0808080808080807e-01;
  /* #39: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #40: @20 = (@2*@19) */
  w20  = (w2*w19);
  /* #41: @20 = (@1*@20) */
  w20  = (w1*w20);
  /* #42: @20 = (@5*@20) */
  w20  = (w5*w20);
  /* #43: @21 = (@4*@6) */
  w21  = (w4*w6);
  /* #44: @22 = (@3*@21) */
  w22  = (w3*w21);
  /* #45: @20 = (@20+@22) */
  w20 += w22;
  /* #46: @20 = (@13*@20) */
  w20  = (w13*w20);
  /* #47: @21 = (@7*@21) */
  w21  = (w7*w21);
  /* #48: @22 = (@4*@20) */
  w22  = (w4*w20);
  /* #49: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #50: @23 = (@0*@6) */
  w23  = (w0*w6);
  /* #51: @22 = (@22-@23) */
  w22 -= w23;
  /* #52: @21 = (@21-@22) */
  w21 -= w22;
  /* #53: @21 = (@21/@10) */
  w21 /= w10;
  /* #54: @8 = (@8/@10) */
  w8 /= w10;
  /* #55: @22 = (2.*@4) */
  w22 = (2.* w4 );
  /* #56: @23 = (@22*@6) */
  w23  = (w22*w6);
  /* #57: @23 = (@11*@23) */
  w23  = (w11*w23);
  /* #58: @23 = (@13*@23) */
  w23  = (w13*w23);
  /* #59: @23 = (@9*@23) */
  w23  = (w9*w23);
  /* #60: @23 = (@8*@23) */
  w23  = (w8*w23);
  /* #61: @21 = (@21-@23) */
  w21 -= w23;
  /* #62: @23 = (@1*@21) */
  w23  = (w1*w21);
  /* #63: @23 = (@4*@23) */
  w23  = (w4*w23);
  /* #64: @6 = (@12*@6) */
  w6  = (w12*w6);
  /* #65: @23 = (@23-@6) */
  w23 -= w6;
  /* #66: @23 = (@13*@23) */
  w23  = (w13*w23);
  /* #67: @20 = (@20-@23) */
  w20 -= w23;
  /* #68: output[1][1] = @20 */
  if (res[1]) res[1][1] = w20;
  /* #69: output[1][2] = @19 */
  if (res[1]) res[1][2] = w19;
  /* #70: output[1][3] = @21 */
  if (res[1]) res[1][3] = w21;
  /* #71: {NULL, @21, @19, @20} = vertsplit(@16) */
  w21 = w16[1];
  w19 = w16[2];
  w20 = w16[3];
  /* #72: output[1][4] = @21 */
  if (res[1]) res[1][4] = w21;
  /* #73: @21 = (@2*@20) */
  w21  = (w2*w20);
  /* #74: @21 = (@1*@21) */
  w21  = (w1*w21);
  /* #75: @21 = (@5*@21) */
  w21  = (w5*w21);
  /* #76: @23 = (@4*@19) */
  w23  = (w4*w19);
  /* #77: @6 = (@3*@23) */
  w6  = (w3*w23);
  /* #78: @21 = (@21+@6) */
  w21 += w6;
  /* #79: @21 = (@13*@21) */
  w21  = (w13*w21);
  /* #80: @23 = (@7*@23) */
  w23  = (w7*w23);
  /* #81: @6 = (@4*@21) */
  w6  = (w4*w21);
  /* #82: @19 = (@5*@19) */
  w19  = (w5*w19);
  /* #83: @24 = (@0*@19) */
  w24  = (w0*w19);
  /* #84: @6 = (@6-@24) */
  w6 -= w24;
  /* #85: @23 = (@23-@6) */
  w23 -= w6;
  /* #86: @23 = (@23/@10) */
  w23 /= w10;
  /* #87: @6 = (@22*@19) */
  w6  = (w22*w19);
  /* #88: @6 = (@11*@6) */
  w6  = (w11*w6);
  /* #89: @6 = (@13*@6) */
  w6  = (w13*w6);
  /* #90: @6 = (@9*@6) */
  w6  = (w9*w6);
  /* #91: @6 = (@8*@6) */
  w6  = (w8*w6);
  /* #92: @23 = (@23-@6) */
  w23 -= w6;
  /* #93: @6 = (@1*@23) */
  w6  = (w1*w23);
  /* #94: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #95: @19 = (@12*@19) */
  w19  = (w12*w19);
  /* #96: @6 = (@6-@19) */
  w6 -= w19;
  /* #97: @6 = (@13*@6) */
  w6  = (w13*w6);
  /* #98: @21 = (@21-@6) */
  w21 -= w6;
  /* #99: output[1][5] = @21 */
  if (res[1]) res[1][5] = w21;
  /* #100: output[1][6] = @20 */
  if (res[1]) res[1][6] = w20;
  /* #101: output[1][7] = @23 */
  if (res[1]) res[1][7] = w23;
  /* #102: {NULL, @23, @20, @21} = vertsplit(@17) */
  w23 = w17[1];
  w20 = w17[2];
  w21 = w17[3];
  /* #103: output[1][8] = @23 */
  if (res[1]) res[1][8] = w23;
  /* #104: @23 = (@2*@21) */
  w23  = (w2*w21);
  /* #105: @23 = (@1*@23) */
  w23  = (w1*w23);
  /* #106: @23 = (@5*@23) */
  w23  = (w5*w23);
  /* #107: @6 = (@4*@20) */
  w6  = (w4*w20);
  /* #108: @19 = (@3*@6) */
  w19  = (w3*w6);
  /* #109: @23 = (@23+@19) */
  w23 += w19;
  /* #110: @23 = (@13*@23) */
  w23  = (w13*w23);
  /* #111: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #112: @19 = (@4*@23) */
  w19  = (w4*w23);
  /* #113: @20 = (@5*@20) */
  w20  = (w5*w20);
  /* #114: @24 = (@0*@20) */
  w24  = (w0*w20);
  /* #115: @19 = (@19-@24) */
  w19 -= w24;
  /* #116: @6 = (@6-@19) */
  w6 -= w19;
  /* #117: @6 = (@6/@10) */
  w6 /= w10;
  /* #118: @19 = (@22*@20) */
  w19  = (w22*w20);
  /* #119: @19 = (@11*@19) */
  w19  = (w11*w19);
  /* #120: @19 = (@13*@19) */
  w19  = (w13*w19);
  /* #121: @19 = (@9*@19) */
  w19  = (w9*w19);
  /* #122: @19 = (@8*@19) */
  w19  = (w8*w19);
  /* #123: @6 = (@6-@19) */
  w6 -= w19;
  /* #124: @19 = (@1*@6) */
  w19  = (w1*w6);
  /* #125: @19 = (@4*@19) */
  w19  = (w4*w19);
  /* #126: @20 = (@12*@20) */
  w20  = (w12*w20);
  /* #127: @19 = (@19-@20) */
  w19 -= w20;
  /* #128: @19 = (@13*@19) */
  w19  = (w13*w19);
  /* #129: @23 = (@23-@19) */
  w23 -= w19;
  /* #130: output[1][9] = @23 */
  if (res[1]) res[1][9] = w23;
  /* #131: output[1][10] = @21 */
  if (res[1]) res[1][10] = w21;
  /* #132: output[1][11] = @6 */
  if (res[1]) res[1][11] = w6;
  /* #133: {NULL, @6, @21, @23} = vertsplit(@18) */
  w6 = w18[1];
  w21 = w18[2];
  w23 = w18[3];
  /* #134: output[1][12] = @6 */
  if (res[1]) res[1][12] = w6;
  /* #135: @6 = (@2*@23) */
  w6  = (w2*w23);
  /* #136: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #137: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #138: @19 = (@4*@21) */
  w19  = (w4*w21);
  /* #139: @20 = (@3*@19) */
  w20  = (w3*w19);
  /* #140: @6 = (@6+@20) */
  w6 += w20;
  /* #141: @6 = (@13*@6) */
  w6  = (w13*w6);
  /* #142: @19 = (@7*@19) */
  w19  = (w7*w19);
  /* #143: @20 = (@4*@6) */
  w20  = (w4*w6);
  /* #144: @21 = (@5*@21) */
  w21  = (w5*w21);
  /* #145: @24 = (@0*@21) */
  w24  = (w0*w21);
  /* #146: @20 = (@20-@24) */
  w20 -= w24;
  /* #147: @19 = (@19-@20) */
  w19 -= w20;
  /* #148: @19 = (@19/@10) */
  w19 /= w10;
  /* #149: @20 = (@22*@21) */
  w20  = (w22*w21);
  /* #150: @20 = (@11*@20) */
  w20  = (w11*w20);
  /* #151: @20 = (@13*@20) */
  w20  = (w13*w20);
  /* #152: @20 = (@9*@20) */
  w20  = (w9*w20);
  /* #153: @20 = (@8*@20) */
  w20  = (w8*w20);
  /* #154: @19 = (@19-@20) */
  w19 -= w20;
  /* #155: @20 = (@1*@19) */
  w20  = (w1*w19);
  /* #156: @20 = (@4*@20) */
  w20  = (w4*w20);
  /* #157: @21 = (@12*@21) */
  w21  = (w12*w21);
  /* #158: @20 = (@20-@21) */
  w20 -= w21;
  /* #159: @20 = (@13*@20) */
  w20  = (w13*w20);
  /* #160: @6 = (@6-@20) */
  w6 -= w20;
  /* #161: output[1][13] = @6 */
  if (res[1]) res[1][13] = w6;
  /* #162: output[1][14] = @23 */
  if (res[1]) res[1][14] = w23;
  /* #163: output[1][15] = @19 */
  if (res[1]) res[1][15] = w19;
  /* #164: @25 = zeros(1x4,2nz) */
  casadi_clear(w25, 2);
  /* #165: @26 = 00 */
  /* #166: @19 = (@13*@4) */
  w19  = (w13*w4);
  /* #167: @19 = (@19/@10) */
  w19 /= w10;
  /* #168: @23 = (@1*@19) */
  w23  = (w1*w19);
  /* #169: @23 = (@4*@23) */
  w23  = (w4*w23);
  /* #170: @23 = (@13*@23) */
  w23  = (w13*w23);
  /* #171: @23 = (@13+@23) */
  w23  = (w13+w23);
  /* #172: @19 = (-@19) */
  w19 = (- w19 );
  /* #173: @27 = vertcat(@26, @23, @26, @19) */
  rr=w27;
  *rr++ = w23;
  *rr++ = w19;
  /* #174: @28 = @27[:2] */
  for (rr=w28, ss=w27+0; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #175: (@25[:2] = @28) */
  for (rr=w25+0, ss=w28; rr!=w25+2; rr+=1) *rr = *ss++;
  /* #176: @25 = @25' */
  /* #177: @18 = dense(@25) */
  casadi_densify(w25, casadi_s0, w18, 0);
  /* #178: @17 = input[2][0] */
  casadi_copy(arg[2], 4, w17);
  /* #179: {NULL, @23, @19, @6} = vertsplit(@17) */
  w23 = w17[1];
  w19 = w17[2];
  w6 = w17[3];
  /* #180: @2 = (@2*@6) */
  w2 *= w6;
  /* #181: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #182: @2 = (@5*@2) */
  w2  = (w5*w2);
  /* #183: @20 = (@4*@19) */
  w20  = (w4*w19);
  /* #184: @3 = (@3*@20) */
  w3 *= w20;
  /* #185: @2 = (@2+@3) */
  w2 += w3;
  /* #186: @2 = (@13*@2) */
  w2  = (w13*w2);
  /* #187: @7 = (@7*@20) */
  w7 *= w20;
  /* #188: @20 = (@4*@2) */
  w20  = (w4*w2);
  /* #189: @5 = (@5*@19) */
  w5 *= w19;
  /* #190: @0 = (@0*@5) */
  w0 *= w5;
  /* #191: @20 = (@20-@0) */
  w20 -= w0;
  /* #192: @7 = (@7-@20) */
  w7 -= w20;
  /* #193: @7 = (@7/@10) */
  w7 /= w10;
  /* #194: @22 = (@22*@5) */
  w22 *= w5;
  /* #195: @11 = (@11*@22) */
  w11 *= w22;
  /* #196: @11 = (@13*@11) */
  w11  = (w13*w11);
  /* #197: @9 = (@9*@11) */
  w9 *= w11;
  /* #198: @8 = (@8*@9) */
  w8 *= w9;
  /* #199: @7 = (@7-@8) */
  w7 -= w8;
  /* #200: @1 = (@1*@7) */
  w1 *= w7;
  /* #201: @4 = (@4*@1) */
  w4 *= w1;
  /* #202: @12 = (@12*@5) */
  w12 *= w5;
  /* #203: @4 = (@4-@12) */
  w4 -= w12;
  /* #204: @13 = (@13*@4) */
  w13 *= w4;
  /* #205: @2 = (@2-@13) */
  w2 -= w13;
  /* #206: @17 = vertcat(@23, @2, @6, @7) */
  rr=w17;
  *rr++ = w23;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w7;
  /* #207: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<4; ++i) (*rr++) += (*cs++);
  /* #208: output[2][0] = @18 */
  casadi_copy(w18, 4, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cartpole_nominal_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int cartpole_nominal_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real cartpole_nominal_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_nominal_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_nominal_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_nominal_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_nominal_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 58;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 58*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
