/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cartpole_nominal_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};

/* cartpole_nominal_expl_ode_fun:(i0[4],i1,i2[0])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #3: @1 = 0.0632813 */
  w1 = 6.3281250000000011e-02;
  /* #4: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #5: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #6: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #7: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #8: @5 = sin(@4) */
  w5 = sin( w4 );
  /* #9: @3 = (@3*@5) */
  w3 *= w5;
  /* #10: @0 = (@0+@3) */
  w0 += w3;
  /* #11: @3 = 1.2375 */
  w3 = 1.2375000000000000e+00;
  /* #12: @0 = (@0/@3) */
  w0 /= w3;
  /* #13: @6 = 9.8 */
  w6 = 9.8000000000000007e+00;
  /* #14: @6 = (@6*@5) */
  w6 *= w5;
  /* #15: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #16: @5 = (@4*@0) */
  w5  = (w4*w0);
  /* #17: @6 = (@6-@5) */
  w6 -= w5;
  /* #18: @5 = 0.5625 */
  w5 = 5.6250000000000000e-01;
  /* #19: @7 = 1.33333 */
  w7 = 1.3333333333333333e+00;
  /* #20: @8 = 0.1125 */
  w8 = 1.1250000000000002e-01;
  /* #21: @9 = sq(@4) */
  w9 = casadi_sq( w4 );
  /* #22: @8 = (@8*@9) */
  w8 *= w9;
  /* #23: @8 = (@8/@3) */
  w8 /= w3;
  /* #24: @7 = (@7-@8) */
  w7 -= w8;
  /* #25: @5 = (@5*@7) */
  w5 *= w7;
  /* #26: @6 = (@6/@5) */
  w6 /= w5;
  /* #27: @1 = (@1*@6) */
  w1 *= w6;
  /* #28: @1 = (@1*@4) */
  w1 *= w4;
  /* #29: @1 = (@1/@3) */
  w1 /= w3;
  /* #30: @0 = (@0-@1) */
  w0 -= w1;
  /* #31: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #32: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #33: output[0][3] = @6 */
  if (res[0]) res[0][3] = w6;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void cartpole_nominal_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cartpole_nominal_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int cartpole_nominal_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cartpole_nominal_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_nominal_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_nominal_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_nominal_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_nominal_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 10;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_nominal_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 10*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
