/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor2D_learned_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};

/* quadrotor2D_learned_expl_ode_fun:(i0[6],i1[2],i2[0])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #3: @1 = sin(@0) */
  w1 = sin( w0 );
  /* #4: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #5: @3 = input[1][1] */
  w3 = arg[1] ? arg[1][1] : 0;
  /* #6: @4 = (@2+@3) */
  w4  = (w2+w3);
  /* #7: @1 = (@1*@4) */
  w1 *= w4;
  /* #8: @5 = 0.01782 */
  w5 = 1.7819999999999999e-02;
  /* #9: @1 = (@1/@5) */
  w1 /= w5;
  /* #10: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #11: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #12: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #13: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #14: @0 = (@0*@4) */
  w0 *= w4;
  /* #15: @0 = (@0/@5) */
  w0 /= w5;
  /* #16: @5 = 9.8 */
  w5 = 9.8000000000000007e+00;
  /* #17: @0 = (@0-@5) */
  w0 -= w5;
  /* #18: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  /* #19: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #20: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  /* #21: @0 = 0.0397 */
  w0 = 3.9699999999999999e-02;
  /* #22: @3 = (@3-@2) */
  w3 -= w2;
  /* #23: @0 = (@0*@3) */
  w0 *= w3;
  /* #24: @3 = 1.12e-05 */
  w3 = 1.1200000000000001e-05;
  /* #25: @0 = (@0/@3) */
  w0 /= w3;
  /* #26: @3 = 1.41421 */
  w3 = 1.4142135623730951e+00;
  /* #27: @0 = (@0/@3) */
  w0 /= w3;
  /* #28: output[0][5] = @0 */
  if (res[0]) res[0][5] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor2D_learned_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 6*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
