/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor2D_learned_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[10] = {8, 1, 0, 6, 1, 3, 4, 5, 6, 7};

/* quadrotor2D_learned_expl_vde_adj:(i0[6],i1[6],i2[2],i3[0])->(o0[8x1,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 6, w0);
  /* #1: {@1, @2, @3, @4, @5, @6} = vertsplit(@0) */
  w1 = w0[0];
  w2 = w0[1];
  w3 = w0[2];
  w4 = w0[3];
  w5 = w0[4];
  w6 = w0[5];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: output[0][1] = @3 */
  if (res[0]) res[0][1] = w3;
  /* #4: @3 = input[0][4] */
  w3 = arg[0] ? arg[0][4] : 0;
  /* #5: @1 = cos(@3) */
  w1 = cos( w3 );
  /* #6: @7 = input[2][0] */
  w7 = arg[2] ? arg[2][0] : 0;
  /* #7: @8 = input[2][1] */
  w8 = arg[2] ? arg[2][1] : 0;
  /* #8: @7 = (@7+@8) */
  w7 += w8;
  /* #9: @8 = 56.1167 */
  w8 = 5.6116722783389456e+01;
  /* #10: @2 = (@8*@2) */
  w2  = (w8*w2);
  /* #11: @9 = (@7*@2) */
  w9  = (w7*w2);
  /* #12: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #13: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #14: @8 = (@8*@4) */
  w8 *= w4;
  /* #15: @7 = (@7*@8) */
  w7 *= w8;
  /* #16: @7 = (@3*@7) */
  w7  = (w3*w7);
  /* #17: @9 = (@9-@7) */
  w9 -= w7;
  /* #18: output[0][2] = @9 */
  if (res[0]) res[0][2] = w9;
  /* #19: output[0][3] = @5 */
  if (res[0]) res[0][3] = w5;
  /* #20: @1 = (@1*@8) */
  w1 *= w8;
  /* #21: @8 = 0.0397 */
  w8 = 3.9699999999999999e-02;
  /* #22: @5 = 89285.7 */
  w5 = 8.9285714285714275e+04;
  /* #23: @9 = 0.707107 */
  w9 = 7.0710678118654746e-01;
  /* #24: @9 = (@9*@6) */
  w9 *= w6;
  /* #25: @5 = (@5*@9) */
  w5 *= w9;
  /* #26: @8 = (@8*@5) */
  w8 *= w5;
  /* #27: @5 = (@1-@8) */
  w5  = (w1-w8);
  /* #28: @3 = (@3*@2) */
  w3 *= w2;
  /* #29: @5 = (@5+@3) */
  w5 += w3;
  /* #30: output[0][4] = @5 */
  if (res[0]) res[0][4] = w5;
  /* #31: @8 = (@8+@1) */
  w8 += w1;
  /* #32: @8 = (@8+@3) */
  w8 += w3;
  /* #33: output[0][5] = @8 */
  if (res[0]) res[0][5] = w8;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor2D_learned_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 15;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 15*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
