/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cartpole_learned_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* External functions */
int adj1_residual_pendulum(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* adj1_residual_pendulum:(i0[1x5],out_o0[1x2,0nz],adj_o0[1x2])->(adj_i0[1x5]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (adj1_residual_pendulum(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* cartpole_learned_expl_vde_adj:(i0[4],i1[4],i2,i3[0])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, w2, w3, w4, *w5=w+5, *w7=w+10, *w8=w+12, w9, w10, *w11=w+18, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[2][0] */
  w4 = arg[2] ? arg[2][0] : 0;
  /* #5: @5 = vertcat(@0, @1, @2, @3, @4) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  /* #6: @5 = @5' */
  /* #7: @6 = zeros(1x2,0nz) */
  /* #8: @7 = zeros(2x1) */
  casadi_clear(w7, 2);
  /* #9: @8 = input[1][0] */
  casadi_copy(arg[1], 4, w8);
  /* #10: {@0, @1, @9, @10} = vertsplit(@8) */
  w0 = w8[0];
  w1 = w8[1];
  w9 = w8[2];
  w10 = w8[3];
  /* #11: (@7[1] += @10) */
  for (rr=w7+1, ss=(&w10); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #12: (@7[0] += @1) */
  for (rr=w7+0, ss=(&w1); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #13: @7 = @7' */
  /* #14: @11 = adj1_residual_pendulum(@5, @6, @7) */
  arg1[0]=w5;
  arg1[1]=0;
  arg1[2]=w7;
  res1[0]=w11;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #15: @11 = @11' */
  /* #16: {@12, @13, @14, @15, @16} = vertsplit(@11) */
  w12 = w11[0];
  w13 = w11[1];
  w14 = w11[2];
  w15 = w11[3];
  w16 = w11[4];
  /* #17: output[0][0] = @12 */
  if (res[0]) res[0][0] = w12;
  /* #18: @13 = (@13+@0) */
  w13 += w0;
  /* #19: output[0][1] = @13 */
  if (res[0]) res[0][1] = w13;
  /* #20: @13 = sin(@2) */
  w13 = sin( w2 );
  /* #21: @0 = 0.02178 */
  w0 = 2.1780000000000001e-02;
  /* #22: @12 = 9.8 */
  w12 = 9.8000000000000007e+00;
  /* #23: @17 = (@12*@13) */
  w17  = (w12*w13);
  /* #24: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #25: @18 = sq(@3) */
  w18 = casadi_sq( w3 );
  /* #26: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #27: @19 = (@18*@13) */
  w19  = (w18*w13);
  /* #28: @4 = (@4+@19) */
  w4 += w19;
  /* #29: @19 = 0.726 */
  w19 = 7.2599999999999998e-01;
  /* #30: @4 = (@4/@19) */
  w4 /= w19;
  /* #31: @20 = (@2*@4) */
  w20  = (w2*w4);
  /* #32: @17 = (@17-@20) */
  w17 -= w20;
  /* #33: @20 = 0.33 */
  w20 = 3.3000000000000002e-01;
  /* #34: @21 = 1.33333 */
  w21 = 1.3333333333333333e+00;
  /* #35: @22 = 0.066 */
  w22 = 6.6000000000000003e-02;
  /* #36: @23 = sq(@2) */
  w23 = casadi_sq( w2 );
  /* #37: @23 = (@22*@23) */
  w23  = (w22*w23);
  /* #38: @23 = (@23/@19) */
  w23 /= w19;
  /* #39: @21 = (@21-@23) */
  w21 -= w23;
  /* #40: @21 = (@20*@21) */
  w21  = (w20*w21);
  /* #41: @17 = (@17/@21) */
  w17 /= w21;
  /* #42: @23 = (@0*@17) */
  w23  = (w0*w17);
  /* #43: @19 = 1.37741 */
  w19 = 1.3774104683195594e+00;
  /* #44: @24 = (@19*@1) */
  w24  = (w19*w1);
  /* #45: @23 = (@23*@24) */
  w23 *= w24;
  /* #46: @23 = (@13*@23) */
  w23  = (w13*w23);
  /* #47: @14 = (@14+@23) */
  w14 += w23;
  /* #48: @23 = (2.*@2) */
  w23 = (2.* w2 );
  /* #49: @17 = (@17/@21) */
  w17 /= w21;
  /* #50: @24 = (@2*@24) */
  w24  = (w2*w24);
  /* #51: @24 = (@0*@24) */
  w24  = (w0*w24);
  /* #52: @10 = (@10-@24) */
  w10 -= w24;
  /* #53: @17 = (@17*@10) */
  w17 *= w10;
  /* #54: @20 = (@20*@17) */
  w20 *= w17;
  /* #55: @20 = (@19*@20) */
  w20  = (w19*w20);
  /* #56: @22 = (@22*@20) */
  w22 *= w20;
  /* #57: @23 = (@23*@22) */
  w23 *= w22;
  /* #58: @23 = (@13*@23) */
  w23  = (w13*w23);
  /* #59: @14 = (@14-@23) */
  w14 -= w23;
  /* #60: @10 = (@10/@21) */
  w10 /= w21;
  /* #61: @4 = (@4*@10) */
  w4 *= w10;
  /* #62: @4 = (@13*@4) */
  w4  = (w13*w4);
  /* #63: @14 = (@14+@4) */
  w14 += w4;
  /* #64: @12 = (@12*@10) */
  w12 *= w10;
  /* #65: @12 = (@2*@12) */
  w12  = (w2*w12);
  /* #66: @14 = (@14+@12) */
  w14 += w12;
  /* #67: @10 = (@2*@10) */
  w10  = (w2*w10);
  /* #68: @1 = (@1-@10) */
  w1 -= w10;
  /* #69: @19 = (@19*@1) */
  w19 *= w1;
  /* #70: @18 = (@18*@19) */
  w18 *= w19;
  /* #71: @2 = (@2*@18) */
  w2 *= w18;
  /* #72: @14 = (@14+@2) */
  w14 += w2;
  /* #73: output[0][2] = @14 */
  if (res[0]) res[0][2] = w14;
  /* #74: @15 = (@15+@9) */
  w15 += w9;
  /* #75: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #76: @13 = (@13*@19) */
  w13 *= w19;
  /* #77: @0 = (@0*@13) */
  w0 *= w13;
  /* #78: @3 = (@3*@0) */
  w3 *= w0;
  /* #79: @15 = (@15+@3) */
  w15 += w3;
  /* #80: output[0][3] = @15 */
  if (res[0]) res[0][3] = w15;
  /* #81: @16 = (@16+@19) */
  w16 += w19;
  /* #82: output[0][4] = @16 */
  if (res[0]) res[0][4] = w16;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cartpole_learned_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int cartpole_learned_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cartpole_learned_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_learned_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_learned_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_learned_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_learned_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 36;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 36*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
