/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cartpole_learned_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[15] = {2, 4, 0, 2, 4, 6, 8, 0, 1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s1[23] = {5, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[18] = {2, 5, 0, 2, 4, 6, 8, 10, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s3[6] = {4, 1, 0, 2, 1, 3};
static const casadi_int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s5[5] = {5, 1, 0, 1, 4};
static const casadi_int casadi_s6[8] = {5, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s8[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s9[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s10[4] = {0, 1, 0, 0};

/* External functions */
int jac_residual_pendulum(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int residual_pendulum(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* residual_pendulum:(i0[1x5])->(o0[1x2]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (residual_pendulum(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* jac_residual_pendulum:(i0[1x5],out_o0[1x2,0nz])->(jac_o0_i0[2x5]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (jac_residual_pendulum(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* cartpole_learned_expl_vde_forw:(i0[4],i1[4x4],i2[4],i3,i4[0])->(o0[4],o1[4x4],o2[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+3, *rr, *ss;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, *w17=w+19, *w18=w+23, *w19=w+28, *w20=w+30, *w21=w+34, *w22=w+50, *w23=w+54, w24, w25, w26, w27, w28, *w30=w+63, *w32=w+71, *w33=w+81, w34, w35, *w36=w+87, *w37=w+89, *w38=w+91, w39, w40, w41;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: @1 = input[3][0] */
  w1 = arg[3] ? arg[3][0] : 0;
  /* #2: @2 = 0.028125 */
  w2 = 2.8125000000000004e-02;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = sq(@3) */
  w4 = casadi_sq( w3 );
  /* #5: @4 = (@2*@4) */
  w4  = (w2*w4);
  /* #6: @5 = input[0][2] */
  w5 = arg[0] ? arg[0][2] : 0;
  /* #7: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #8: @7 = (@4*@6) */
  w7  = (w4*w6);
  /* #9: @7 = (@1+@7) */
  w7  = (w1+w7);
  /* #10: @8 = 0.825 */
  w8 = 8.2499999999999996e-01;
  /* #11: @7 = (@7/@8) */
  w7 /= w8;
  /* #12: @9 = 9.8 */
  w9 = 9.8000000000000007e+00;
  /* #13: @10 = (@9*@6) */
  w10  = (w9*w6);
  /* #14: @11 = cos(@5) */
  w11 = cos( w5 );
  /* #15: @12 = (@11*@7) */
  w12  = (w11*w7);
  /* #16: @10 = (@10-@12) */
  w10 -= w12;
  /* #17: @12 = 0.375 */
  w12 = 3.7500000000000000e-01;
  /* #18: @13 = 1.33333 */
  w13 = 1.3333333333333333e+00;
  /* #19: @14 = 0.075 */
  w14 = 7.5000000000000011e-02;
  /* #20: @15 = sq(@11) */
  w15 = casadi_sq( w11 );
  /* #21: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #22: @15 = (@15/@8) */
  w15 /= w8;
  /* #23: @13 = (@13-@15) */
  w13 -= w15;
  /* #24: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #25: @10 = (@10/@13) */
  w10 /= w13;
  /* #26: @15 = (@2*@10) */
  w15  = (w2*w10);
  /* #27: @16 = (@15*@11) */
  w16  = (w15*w11);
  /* #28: @16 = (@16/@8) */
  w16 /= w8;
  /* #29: @16 = (@7-@16) */
  w16  = (w7-w16);
  /* #30: @17 = vertcat(@0, @16, @3, @10) */
  rr=w17;
  *rr++ = w0;
  *rr++ = w16;
  *rr++ = w3;
  *rr++ = w10;
  /* #31: @16 = 0 */
  w16 = 0.;
  /* #32: @8 = input[0][0] */
  w8 = arg[0] ? arg[0][0] : 0;
  /* #33: @18 = vertcat(@8, @0, @5, @3, @1) */
  rr=w18;
  *rr++ = w8;
  *rr++ = w0;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w1;
  /* #34: @18 = @18' */
  /* #35: @19 = residual_pendulum(@18) */
  arg1[0]=w18;
  res1[0]=w19;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #36: @19 = @19' */
  /* #37: @8 = @19[0] */
  for (rr=(&w8), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #38: @0 = @19[1] */
  for (rr=(&w0), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #39: @20 = vertcat(@16, @8, @16, @0) */
  rr=w20;
  *rr++ = w16;
  *rr++ = w8;
  *rr++ = w16;
  *rr++ = w0;
  /* #40: @17 = (@17+@20) */
  for (i=0, rr=w17, cs=w20; i<4; ++i) (*rr++) += (*cs++);
  /* #41: output[0][0] = @17 */
  casadi_copy(w17, 4, res[0]);
  /* #42: @21 = input[1][0] */
  casadi_copy(arg[1], 16, w21);
  /* #43: {@17, @20, @22, @23} = horzsplit(@21) */
  casadi_copy(w21, 4, w17);
  casadi_copy(w21+4, 4, w20);
  casadi_copy(w21+8, 4, w22);
  casadi_copy(w21+12, 4, w23);
  /* #44: {@16, @8, @0, @5} = vertsplit(@17) */
  w16 = w17[0];
  w8 = w17[1];
  w0 = w17[2];
  w5 = w17[3];
  /* #45: @1 = 1.21212 */
  w1 = 1.2121212121212122e+00;
  /* #46: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #47: @24 = (@3*@5) */
  w24  = (w3*w5);
  /* #48: @24 = (@2*@24) */
  w24  = (w2*w24);
  /* #49: @24 = (@6*@24) */
  w24  = (w6*w24);
  /* #50: @25 = (@11*@0) */
  w25  = (w11*w0);
  /* #51: @26 = (@4*@25) */
  w26  = (w4*w25);
  /* #52: @24 = (@24+@26) */
  w24 += w26;
  /* #53: @24 = (@1*@24) */
  w24  = (w1*w24);
  /* #54: @25 = (@9*@25) */
  w25  = (w9*w25);
  /* #55: @26 = (@11*@24) */
  w26  = (w11*w24);
  /* #56: @27 = (@6*@0) */
  w27  = (w6*w0);
  /* #57: @28 = (@7*@27) */
  w28  = (w7*w27);
  /* #58: @26 = (@26-@28) */
  w26 -= w28;
  /* #59: @25 = (@25-@26) */
  w25 -= w26;
  /* #60: @25 = (@25/@13) */
  w25 /= w13;
  /* #61: @10 = (@10/@13) */
  w10 /= w13;
  /* #62: @26 = (2.*@11) */
  w26 = (2.* w11 );
  /* #63: @28 = (@26*@27) */
  w28  = (w26*w27);
  /* #64: @28 = (@14*@28) */
  w28  = (w14*w28);
  /* #65: @28 = (@1*@28) */
  w28  = (w1*w28);
  /* #66: @28 = (@12*@28) */
  w28  = (w12*w28);
  /* #67: @28 = (@10*@28) */
  w28  = (w10*w28);
  /* #68: @25 = (@25-@28) */
  w25 -= w28;
  /* #69: @28 = (@2*@25) */
  w28  = (w2*w25);
  /* #70: @28 = (@11*@28) */
  w28  = (w11*w28);
  /* #71: @27 = (@15*@27) */
  w27  = (w15*w27);
  /* #72: @28 = (@28-@27) */
  w28 -= w27;
  /* #73: @28 = (@1*@28) */
  w28  = (w1*w28);
  /* #74: @24 = (@24-@28) */
  w24 -= w28;
  /* #75: @17 = vertcat(@8, @24, @5, @25) */
  rr=w17;
  *rr++ = w8;
  *rr++ = w24;
  *rr++ = w5;
  *rr++ = w25;
  /* #76: @29 = 00 */
  /* #77: @30 = zeros(2x4) */
  casadi_clear(w30, 8);
  /* #78: @31 = zeros(1x2,0nz) */
  /* #79: @32 = jac_residual_pendulum(@18, @31) */
  arg1[0]=w18;
  arg1[1]=0;
  res1[0]=w32;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #80: @33 = vertcat(@16, @8, @0, @5, @29) */
  rr=w33;
  *rr++ = w16;
  *rr++ = w8;
  *rr++ = w0;
  *rr++ = w5;
  /* #81: {@16, @8, @0, @5} = vertsplit(@20) */
  w16 = w20[0];
  w8 = w20[1];
  w0 = w20[2];
  w5 = w20[3];
  /* #82: @20 = vertcat(@16, @8, @0, @5, @29) */
  rr=w20;
  *rr++ = w16;
  *rr++ = w8;
  *rr++ = w0;
  *rr++ = w5;
  /* #83: {@16, @24, @25, @28} = vertsplit(@22) */
  w16 = w22[0];
  w24 = w22[1];
  w25 = w22[2];
  w28 = w22[3];
  /* #84: @22 = vertcat(@16, @24, @25, @28, @29) */
  rr=w22;
  *rr++ = w16;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w28;
  /* #85: {@16, @27, @34, @35} = vertsplit(@23) */
  w16 = w23[0];
  w27 = w23[1];
  w34 = w23[2];
  w35 = w23[3];
  /* #86: @23 = vertcat(@16, @27, @34, @35, @29) */
  rr=w23;
  *rr++ = w16;
  *rr++ = w27;
  *rr++ = w34;
  *rr++ = w35;
  /* #87: @21 = horzcat(@33, @20, @22, @23) */
  rr=w21;
  for (i=0, cs=w33; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<4; ++i) *rr++ = *cs++;
  /* #88: @30 = mac(@32,@21,@30) */
  casadi_mtimes(w32, casadi_s2, w21, casadi_s1, w30, casadi_s0, w, 0);
  /* #89: {@19, @36, @37, @38} = horzsplit(@30) */
  casadi_copy(w30, 2, w19);
  casadi_copy(w30+2, 2, w36);
  casadi_copy(w30+4, 2, w37);
  casadi_copy(w30+6, 2, w38);
  /* #90: @16 = @19[0] */
  for (rr=(&w16), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #91: @39 = @19[1] */
  for (rr=(&w39), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #92: @19 = vertcat(@29, @16, @29, @39) */
  rr=w19;
  *rr++ = w16;
  *rr++ = w39;
  /* #93: @33 = dense(@19) */
  casadi_densify(w19, casadi_s3, w33, 0);
  /* #94: @17 = (@17+@33) */
  for (i=0, rr=w17, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #95: output[1][0] = @17 */
  casadi_copy(w17, 4, res[1]);
  /* #96: @16 = (@3*@5) */
  w16  = (w3*w5);
  /* #97: @16 = (@2*@16) */
  w16  = (w2*w16);
  /* #98: @16 = (@6*@16) */
  w16  = (w6*w16);
  /* #99: @39 = (@11*@0) */
  w39  = (w11*w0);
  /* #100: @40 = (@4*@39) */
  w40  = (w4*w39);
  /* #101: @16 = (@16+@40) */
  w16 += w40;
  /* #102: @16 = (@1*@16) */
  w16  = (w1*w16);
  /* #103: @39 = (@9*@39) */
  w39  = (w9*w39);
  /* #104: @40 = (@11*@16) */
  w40  = (w11*w16);
  /* #105: @0 = (@6*@0) */
  w0  = (w6*w0);
  /* #106: @41 = (@7*@0) */
  w41  = (w7*w0);
  /* #107: @40 = (@40-@41) */
  w40 -= w41;
  /* #108: @39 = (@39-@40) */
  w39 -= w40;
  /* #109: @39 = (@39/@13) */
  w39 /= w13;
  /* #110: @40 = (@26*@0) */
  w40  = (w26*w0);
  /* #111: @40 = (@14*@40) */
  w40  = (w14*w40);
  /* #112: @40 = (@1*@40) */
  w40  = (w1*w40);
  /* #113: @40 = (@12*@40) */
  w40  = (w12*w40);
  /* #114: @40 = (@10*@40) */
  w40  = (w10*w40);
  /* #115: @39 = (@39-@40) */
  w39 -= w40;
  /* #116: @40 = (@2*@39) */
  w40  = (w2*w39);
  /* #117: @40 = (@11*@40) */
  w40  = (w11*w40);
  /* #118: @0 = (@15*@0) */
  w0  = (w15*w0);
  /* #119: @40 = (@40-@0) */
  w40 -= w0;
  /* #120: @40 = (@1*@40) */
  w40  = (w1*w40);
  /* #121: @16 = (@16-@40) */
  w16 -= w40;
  /* #122: @17 = vertcat(@8, @16, @5, @39) */
  rr=w17;
  *rr++ = w8;
  *rr++ = w16;
  *rr++ = w5;
  *rr++ = w39;
  /* #123: @8 = @36[0] */
  for (rr=(&w8), ss=w36+0; ss!=w36+1; ss+=1) *rr++ = *ss;
  /* #124: @16 = @36[1] */
  for (rr=(&w16), ss=w36+1; ss!=w36+2; ss+=1) *rr++ = *ss;
  /* #125: @36 = vertcat(@29, @8, @29, @16) */
  rr=w36;
  *rr++ = w8;
  *rr++ = w16;
  /* #126: @33 = dense(@36) */
  casadi_densify(w36, casadi_s3, w33, 0);
  /* #127: @17 = (@17+@33) */
  for (i=0, rr=w17, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #128: output[1][1] = @17 */
  if (res[1]) casadi_copy(w17, 4, res[1]+4);
  /* #129: @8 = (@3*@28) */
  w8  = (w3*w28);
  /* #130: @8 = (@2*@8) */
  w8  = (w2*w8);
  /* #131: @8 = (@6*@8) */
  w8  = (w6*w8);
  /* #132: @16 = (@11*@25) */
  w16  = (w11*w25);
  /* #133: @5 = (@4*@16) */
  w5  = (w4*w16);
  /* #134: @8 = (@8+@5) */
  w8 += w5;
  /* #135: @8 = (@1*@8) */
  w8  = (w1*w8);
  /* #136: @16 = (@9*@16) */
  w16  = (w9*w16);
  /* #137: @5 = (@11*@8) */
  w5  = (w11*w8);
  /* #138: @25 = (@6*@25) */
  w25  = (w6*w25);
  /* #139: @39 = (@7*@25) */
  w39  = (w7*w25);
  /* #140: @5 = (@5-@39) */
  w5 -= w39;
  /* #141: @16 = (@16-@5) */
  w16 -= w5;
  /* #142: @16 = (@16/@13) */
  w16 /= w13;
  /* #143: @5 = (@26*@25) */
  w5  = (w26*w25);
  /* #144: @5 = (@14*@5) */
  w5  = (w14*w5);
  /* #145: @5 = (@1*@5) */
  w5  = (w1*w5);
  /* #146: @5 = (@12*@5) */
  w5  = (w12*w5);
  /* #147: @5 = (@10*@5) */
  w5  = (w10*w5);
  /* #148: @16 = (@16-@5) */
  w16 -= w5;
  /* #149: @5 = (@2*@16) */
  w5  = (w2*w16);
  /* #150: @5 = (@11*@5) */
  w5  = (w11*w5);
  /* #151: @25 = (@15*@25) */
  w25  = (w15*w25);
  /* #152: @5 = (@5-@25) */
  w5 -= w25;
  /* #153: @5 = (@1*@5) */
  w5  = (w1*w5);
  /* #154: @8 = (@8-@5) */
  w8 -= w5;
  /* #155: @17 = vertcat(@24, @8, @28, @16) */
  rr=w17;
  *rr++ = w24;
  *rr++ = w8;
  *rr++ = w28;
  *rr++ = w16;
  /* #156: @24 = @37[0] */
  for (rr=(&w24), ss=w37+0; ss!=w37+1; ss+=1) *rr++ = *ss;
  /* #157: @8 = @37[1] */
  for (rr=(&w8), ss=w37+1; ss!=w37+2; ss+=1) *rr++ = *ss;
  /* #158: @37 = vertcat(@29, @24, @29, @8) */
  rr=w37;
  *rr++ = w24;
  *rr++ = w8;
  /* #159: @33 = dense(@37) */
  casadi_densify(w37, casadi_s3, w33, 0);
  /* #160: @17 = (@17+@33) */
  for (i=0, rr=w17, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #161: output[1][2] = @17 */
  if (res[1]) casadi_copy(w17, 4, res[1]+8);
  /* #162: @24 = (@3*@35) */
  w24  = (w3*w35);
  /* #163: @24 = (@2*@24) */
  w24  = (w2*w24);
  /* #164: @24 = (@6*@24) */
  w24  = (w6*w24);
  /* #165: @8 = (@11*@34) */
  w8  = (w11*w34);
  /* #166: @28 = (@4*@8) */
  w28  = (w4*w8);
  /* #167: @24 = (@24+@28) */
  w24 += w28;
  /* #168: @24 = (@1*@24) */
  w24  = (w1*w24);
  /* #169: @8 = (@9*@8) */
  w8  = (w9*w8);
  /* #170: @28 = (@11*@24) */
  w28  = (w11*w24);
  /* #171: @34 = (@6*@34) */
  w34  = (w6*w34);
  /* #172: @16 = (@7*@34) */
  w16  = (w7*w34);
  /* #173: @28 = (@28-@16) */
  w28 -= w16;
  /* #174: @8 = (@8-@28) */
  w8 -= w28;
  /* #175: @8 = (@8/@13) */
  w8 /= w13;
  /* #176: @28 = (@26*@34) */
  w28  = (w26*w34);
  /* #177: @28 = (@14*@28) */
  w28  = (w14*w28);
  /* #178: @28 = (@1*@28) */
  w28  = (w1*w28);
  /* #179: @28 = (@12*@28) */
  w28  = (w12*w28);
  /* #180: @28 = (@10*@28) */
  w28  = (w10*w28);
  /* #181: @8 = (@8-@28) */
  w8 -= w28;
  /* #182: @28 = (@2*@8) */
  w28  = (w2*w8);
  /* #183: @28 = (@11*@28) */
  w28  = (w11*w28);
  /* #184: @34 = (@15*@34) */
  w34  = (w15*w34);
  /* #185: @28 = (@28-@34) */
  w28 -= w34;
  /* #186: @28 = (@1*@28) */
  w28  = (w1*w28);
  /* #187: @24 = (@24-@28) */
  w24 -= w28;
  /* #188: @17 = vertcat(@27, @24, @35, @8) */
  rr=w17;
  *rr++ = w27;
  *rr++ = w24;
  *rr++ = w35;
  *rr++ = w8;
  /* #189: @27 = @38[0] */
  for (rr=(&w27), ss=w38+0; ss!=w38+1; ss+=1) *rr++ = *ss;
  /* #190: @24 = @38[1] */
  for (rr=(&w24), ss=w38+1; ss!=w38+2; ss+=1) *rr++ = *ss;
  /* #191: @38 = vertcat(@29, @27, @29, @24) */
  rr=w38;
  *rr++ = w27;
  *rr++ = w24;
  /* #192: @33 = dense(@38) */
  casadi_densify(w38, casadi_s3, w33, 0);
  /* #193: @17 = (@17+@33) */
  for (i=0, rr=w17, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #194: output[1][3] = @17 */
  if (res[1]) casadi_copy(w17, 4, res[1]+12);
  /* #195: @38 = zeros(1x4,2nz) */
  casadi_clear(w38, 2);
  /* #196: @27 = (@1*@11) */
  w27  = (w1*w11);
  /* #197: @27 = (@27/@13) */
  w27 /= w13;
  /* #198: @24 = (@2*@27) */
  w24  = (w2*w27);
  /* #199: @24 = (@11*@24) */
  w24  = (w11*w24);
  /* #200: @24 = (@1*@24) */
  w24  = (w1*w24);
  /* #201: @24 = (@1+@24) */
  w24  = (w1+w24);
  /* #202: @27 = (-@27) */
  w27 = (- w27 );
  /* #203: @37 = vertcat(@29, @24, @29, @27) */
  rr=w37;
  *rr++ = w24;
  *rr++ = w27;
  /* #204: @36 = zeros(2x1) */
  casadi_clear(w36, 2);
  /* #205: @24 = 1 */
  w24 = 1.;
  /* #206: @27 = vertcat(@29, @29, @29, @29, @24) */
  rr=(&w27);
  *rr++ = w24;
  /* #207: @19 = mac(@32,@27,@36) */
  casadi_copy(w36, 2, w19);
  casadi_mtimes(w32, casadi_s2, (&w27), casadi_s5, w19, casadi_s4, w, 0);
  /* #208: @27 = @19[0] */
  for (rr=(&w27), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #209: @24 = @19[1] */
  for (rr=(&w24), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #210: @19 = vertcat(@29, @27, @29, @24) */
  rr=w19;
  *rr++ = w27;
  *rr++ = w24;
  /* #211: @37 = (@37+@19) */
  for (i=0, rr=w37, cs=w19; i<2; ++i) (*rr++) += (*cs++);
  /* #212: @19 = @37[:2] */
  for (rr=w19, ss=w37+0; ss!=w37+2; ss+=1) *rr++ = *ss;
  /* #213: (@38[:2] = @19) */
  for (rr=w38+0, ss=w19; rr!=w38+2; rr+=1) *rr = *ss++;
  /* #214: @38 = @38' */
  /* #215: @17 = dense(@38) */
  casadi_densify(w38, casadi_s3, w17, 0);
  /* #216: @33 = input[2][0] */
  casadi_copy(arg[2], 4, w33);
  /* #217: {@27, @24, @35, @8} = vertsplit(@33) */
  w27 = w33[0];
  w24 = w33[1];
  w35 = w33[2];
  w8 = w33[3];
  /* #218: @3 = (@3*@8) */
  w3 *= w8;
  /* #219: @3 = (@2*@3) */
  w3  = (w2*w3);
  /* #220: @3 = (@6*@3) */
  w3  = (w6*w3);
  /* #221: @28 = (@11*@35) */
  w28  = (w11*w35);
  /* #222: @4 = (@4*@28) */
  w4 *= w28;
  /* #223: @3 = (@3+@4) */
  w3 += w4;
  /* #224: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #225: @9 = (@9*@28) */
  w9 *= w28;
  /* #226: @28 = (@11*@3) */
  w28  = (w11*w3);
  /* #227: @6 = (@6*@35) */
  w6 *= w35;
  /* #228: @7 = (@7*@6) */
  w7 *= w6;
  /* #229: @28 = (@28-@7) */
  w28 -= w7;
  /* #230: @9 = (@9-@28) */
  w9 -= w28;
  /* #231: @9 = (@9/@13) */
  w9 /= w13;
  /* #232: @26 = (@26*@6) */
  w26 *= w6;
  /* #233: @14 = (@14*@26) */
  w14 *= w26;
  /* #234: @14 = (@1*@14) */
  w14  = (w1*w14);
  /* #235: @12 = (@12*@14) */
  w12 *= w14;
  /* #236: @10 = (@10*@12) */
  w10 *= w12;
  /* #237: @9 = (@9-@10) */
  w9 -= w10;
  /* #238: @2 = (@2*@9) */
  w2 *= w9;
  /* #239: @11 = (@11*@2) */
  w11 *= w2;
  /* #240: @15 = (@15*@6) */
  w15 *= w6;
  /* #241: @11 = (@11-@15) */
  w11 -= w15;
  /* #242: @1 = (@1*@11) */
  w1 *= w11;
  /* #243: @3 = (@3-@1) */
  w3 -= w1;
  /* #244: @33 = vertcat(@24, @3, @8, @9) */
  rr=w33;
  *rr++ = w24;
  *rr++ = w3;
  *rr++ = w8;
  *rr++ = w9;
  /* #245: @20 = vertcat(@27, @24, @35, @8, @29) */
  rr=w20;
  *rr++ = w27;
  *rr++ = w24;
  *rr++ = w35;
  *rr++ = w8;
  /* #246: @36 = mac(@32,@20,@36) */
  casadi_mtimes(w32, casadi_s2, w20, casadi_s6, w36, casadi_s4, w, 0);
  /* #247: @27 = @36[0] */
  for (rr=(&w27), ss=w36+0; ss!=w36+1; ss+=1) *rr++ = *ss;
  /* #248: @24 = @36[1] */
  for (rr=(&w24), ss=w36+1; ss!=w36+2; ss+=1) *rr++ = *ss;
  /* #249: @36 = vertcat(@29, @27, @29, @24) */
  rr=w36;
  *rr++ = w27;
  *rr++ = w24;
  /* #250: @20 = dense(@36) */
  casadi_densify(w36, casadi_s3, w20, 0);
  /* #251: @33 = (@33+@20) */
  for (i=0, rr=w33, cs=w20; i<4; ++i) (*rr++) += (*cs++);
  /* #252: @17 = (@17+@33) */
  for (i=0, rr=w17, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #253: output[2][0] = @17 */
  casadi_copy(w17, 4, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cartpole_learned_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int cartpole_learned_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real cartpole_learned_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_learned_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_learned_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_learned_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s7;
    case 3: return casadi_s9;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_learned_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 96;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 96*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
