/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor2D_learned_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};

/* External functions */
int residual_quadrotor2D(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* residual_quadrotor2D:(i0[1x8])->(o0[1x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (residual_quadrotor2D(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* quadrotor2D_learned_expl_ode_fun:(i0[6],i1[2],i2[0])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+3, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, *w10=w+10, *w11=w+16, *w12=w+24, *w13=w+27;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #2: @2 = sin(@1) */
  w2 = sin( w1 );
  /* #3: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #4: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #5: @5 = (@3+@4) */
  w5  = (w3+w4);
  /* #6: @2 = (@2*@5) */
  w2 *= w5;
  /* #7: @6 = 0.01782 */
  w6 = 1.7819999999999999e-02;
  /* #8: @2 = (@2/@6) */
  w2 /= w6;
  /* #9: @7 = input[0][3] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #10: @8 = cos(@1) */
  w8 = cos( w1 );
  /* #11: @8 = (@8*@5) */
  w8 *= w5;
  /* #12: @8 = (@8/@6) */
  w8 /= w6;
  /* #13: @6 = 9.8 */
  w6 = 9.8000000000000007e+00;
  /* #14: @8 = (@8-@6) */
  w8 -= w6;
  /* #15: @6 = input[0][5] */
  w6 = arg[0] ? arg[0][5] : 0;
  /* #16: @5 = 0.0397 */
  w5 = 3.9699999999999999e-02;
  /* #17: @9 = (@4-@3) */
  w9  = (w4-w3);
  /* #18: @5 = (@5*@9) */
  w5 *= w9;
  /* #19: @9 = 1.12e-05 */
  w9 = 1.1200000000000001e-05;
  /* #20: @5 = (@5/@9) */
  w5 /= w9;
  /* #21: @9 = 1.41421 */
  w9 = 1.4142135623730951e+00;
  /* #22: @5 = (@5/@9) */
  w5 /= w9;
  /* #23: @10 = vertcat(@0, @2, @7, @8, @6, @5) */
  rr=w10;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w6;
  *rr++ = w5;
  /* #24: @2 = 0 */
  w2 = 0.;
  /* #25: @8 = input[0][0] */
  w8 = arg[0] ? arg[0][0] : 0;
  /* #26: @5 = input[0][2] */
  w5 = arg[0] ? arg[0][2] : 0;
  /* #27: @11 = vertcat(@8, @0, @5, @7, @1, @6, @3, @4) */
  rr=w11;
  *rr++ = w8;
  *rr++ = w0;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w1;
  *rr++ = w6;
  *rr++ = w3;
  *rr++ = w4;
  /* #28: @11 = @11' */
  /* #29: @12 = residual_quadrotor2D(@11) */
  arg1[0]=w11;
  res1[0]=w12;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #30: @12 = @12' */
  /* #31: @8 = @12[0] */
  for (rr=(&w8), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #32: @0 = @12[1] */
  for (rr=(&w0), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #33: @5 = @12[2] */
  for (rr=(&w5), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #34: @13 = vertcat(@2, @8, @2, @0, @2, @5) */
  rr=w13;
  *rr++ = w2;
  *rr++ = w8;
  *rr++ = w2;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w5;
  /* #35: @10 = (@10+@13) */
  for (i=0, rr=w10, cs=w13; i<6; ++i) (*rr++) += (*cs++);
  /* #36: output[0][0] = @10 */
  casadi_copy(w10, 6, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor2D_learned_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 33;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 33*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
