/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor2D_learned_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {6, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[27] = {3, 6, 0, 3, 6, 9, 12, 15, 18, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[45] = {8, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[35] = {3, 8, 0, 3, 6, 9, 12, 15, 18, 21, 24, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[7] = {6, 1, 0, 3, 1, 3, 5};
static const casadi_int casadi_s5[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[7] = {8, 2, 0, 1, 2, 6, 7};
static const casadi_int casadi_s7[11] = {6, 2, 0, 3, 6, 1, 3, 5, 1, 3, 5};
static const casadi_int casadi_s8[15] = {2, 6, 0, 0, 2, 2, 4, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s9[17] = {8, 2, 0, 6, 12, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s10[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s11[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s12[17] = {6, 2, 0, 6, 12, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s13[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s14[4] = {0, 1, 0, 0};

/* External functions */
int jac_residual_quadrotor2D(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int residual_quadrotor2D(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* residual_quadrotor2D:(i0[1x8])->(o0[1x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (residual_quadrotor2D(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* jac_residual_quadrotor2D:(i0[1x8],out_o0[1x3,0nz])->(jac_o0_i0[3x8]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (jac_residual_quadrotor2D(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* quadrotor2D_learned_expl_vde_forw:(i0[6],i1[6x6],i2[6x2],i3[2],i4[0])->(o0[6],o1[6x6],o2[6x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+3, *rr, *ss;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+17, *w15=w+23, *w16=w+31, *w17=w+34, *w18=w+40, *w19=w+76, *w20=w+82, *w21=w+88, *w22=w+94, *w24=w+100, *w25=w+105, *w27=w+123, *w28=w+147, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, *w42=w+166, *w43=w+169, *w44=w+172, *w45=w+175, *w46=w+178, w47, *w48=w+182, *w49=w+184, *w50=w+196;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #2: @2 = sin(@1) */
  w2 = sin( w1 );
  /* #3: @3 = input[3][0] */
  w3 = arg[3] ? arg[3][0] : 0;
  /* #4: @4 = input[3][1] */
  w4 = arg[3] ? arg[3][1] : 0;
  /* #5: @5 = (@3+@4) */
  w5  = (w3+w4);
  /* #6: @6 = (@2*@5) */
  w6  = (w2*w5);
  /* #7: @7 = 0.01782 */
  w7 = 1.7819999999999999e-02;
  /* #8: @6 = (@6/@7) */
  w6 /= w7;
  /* #9: @8 = input[0][3] */
  w8 = arg[0] ? arg[0][3] : 0;
  /* #10: @9 = cos(@1) */
  w9 = cos( w1 );
  /* #11: @10 = (@9*@5) */
  w10  = (w9*w5);
  /* #12: @10 = (@10/@7) */
  w10 /= w7;
  /* #13: @7 = 9.8 */
  w7 = 9.8000000000000007e+00;
  /* #14: @10 = (@10-@7) */
  w10 -= w7;
  /* #15: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #16: @11 = 0.0397 */
  w11 = 3.9699999999999999e-02;
  /* #17: @12 = (@4-@3) */
  w12  = (w4-w3);
  /* #18: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #19: @13 = 1.12e-05 */
  w13 = 1.1200000000000001e-05;
  /* #20: @12 = (@12/@13) */
  w12 /= w13;
  /* #21: @13 = 1.41421 */
  w13 = 1.4142135623730951e+00;
  /* #22: @12 = (@12/@13) */
  w12 /= w13;
  /* #23: @14 = vertcat(@0, @6, @8, @10, @7, @12) */
  rr=w14;
  *rr++ = w0;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w7;
  *rr++ = w12;
  /* #24: @6 = 0 */
  w6 = 0.;
  /* #25: @10 = input[0][0] */
  w10 = arg[0] ? arg[0][0] : 0;
  /* #26: @12 = input[0][2] */
  w12 = arg[0] ? arg[0][2] : 0;
  /* #27: @15 = vertcat(@10, @0, @12, @8, @1, @7, @3, @4) */
  rr=w15;
  *rr++ = w10;
  *rr++ = w0;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w1;
  *rr++ = w7;
  *rr++ = w3;
  *rr++ = w4;
  /* #28: @15 = @15' */
  /* #29: @16 = residual_quadrotor2D(@15) */
  arg1[0]=w15;
  res1[0]=w16;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #30: @16 = @16' */
  /* #31: @10 = @16[0] */
  for (rr=(&w10), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #32: @0 = @16[1] */
  for (rr=(&w0), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #33: @12 = @16[2] */
  for (rr=(&w12), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #34: @17 = vertcat(@6, @10, @6, @0, @6, @12) */
  rr=w17;
  *rr++ = w6;
  *rr++ = w10;
  *rr++ = w6;
  *rr++ = w0;
  *rr++ = w6;
  *rr++ = w12;
  /* #35: @14 = (@14+@17) */
  for (i=0, rr=w14, cs=w17; i<6; ++i) (*rr++) += (*cs++);
  /* #36: output[0][0] = @14 */
  casadi_copy(w14, 6, res[0]);
  /* #37: @18 = input[1][0] */
  casadi_copy(arg[1], 36, w18);
  /* #38: {@14, @17, @19, @20, @21, @22} = horzsplit(@18) */
  casadi_copy(w18, 6, w14);
  casadi_copy(w18+6, 6, w17);
  casadi_copy(w18+12, 6, w19);
  casadi_copy(w18+18, 6, w20);
  casadi_copy(w18+24, 6, w21);
  casadi_copy(w18+30, 6, w22);
  /* #39: {@6, @10, @0, @12, @8, @1} = vertsplit(@14) */
  w6 = w14[0];
  w10 = w14[1];
  w0 = w14[2];
  w12 = w14[3];
  w8 = w14[4];
  w1 = w14[5];
  /* #40: @7 = 56.1167 */
  w7 = 5.6116722783389456e+01;
  /* #41: @3 = (@9*@8) */
  w3  = (w9*w8);
  /* #42: @3 = (@5*@3) */
  w3  = (w5*w3);
  /* #43: @3 = (@7*@3) */
  w3  = (w7*w3);
  /* #44: @4 = (@2*@8) */
  w4  = (w2*w8);
  /* #45: @4 = (@5*@4) */
  w4  = (w5*w4);
  /* #46: @4 = (@7*@4) */
  w4  = (w7*w4);
  /* #47: @4 = (-@4) */
  w4 = (- w4 );
  /* #48: @23 = 00 */
  /* #49: @24 = vertcat(@10, @3, @12, @4, @1, @23) */
  rr=w24;
  *rr++ = w10;
  *rr++ = w3;
  *rr++ = w12;
  *rr++ = w4;
  *rr++ = w1;
  /* #50: @14 = dense(@24) */
  casadi_densify(w24, casadi_s0, w14, 0);
  /* #51: @25 = zeros(3x6) */
  casadi_clear(w25, 18);
  /* #52: @26 = zeros(1x3,0nz) */
  /* #53: @27 = jac_residual_quadrotor2D(@15, @26) */
  arg1[0]=w15;
  arg1[1]=0;
  res1[0]=w27;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #54: @28 = vertcat(@6, @10, @0, @12, @8, @1, @23, @23) */
  rr=w28;
  *rr++ = w6;
  *rr++ = w10;
  *rr++ = w0;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w1;
  /* #55: {@6, @10, @0, @12, @8, @1} = vertsplit(@17) */
  w6 = w17[0];
  w10 = w17[1];
  w0 = w17[2];
  w12 = w17[3];
  w8 = w17[4];
  w1 = w17[5];
  /* #56: @17 = vertcat(@6, @10, @0, @12, @8, @1, @23, @23) */
  rr=w17;
  *rr++ = w6;
  *rr++ = w10;
  *rr++ = w0;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w1;
  /* #57: {@6, @0, @3, @4, @13, @29} = vertsplit(@19) */
  w6 = w19[0];
  w0 = w19[1];
  w3 = w19[2];
  w4 = w19[3];
  w13 = w19[4];
  w29 = w19[5];
  /* #58: @19 = vertcat(@6, @0, @3, @4, @13, @29, @23, @23) */
  rr=w19;
  *rr++ = w6;
  *rr++ = w0;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w13;
  *rr++ = w29;
  /* #59: {@6, @3, @30, @31, @32, @33} = vertsplit(@20) */
  w6 = w20[0];
  w3 = w20[1];
  w30 = w20[2];
  w31 = w20[3];
  w32 = w20[4];
  w33 = w20[5];
  /* #60: @20 = vertcat(@6, @3, @30, @31, @32, @33, @23, @23) */
  rr=w20;
  *rr++ = w6;
  *rr++ = w3;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  /* #61: {@6, @30, @34, @35, @36, @37} = vertsplit(@21) */
  w6 = w21[0];
  w30 = w21[1];
  w34 = w21[2];
  w35 = w21[3];
  w36 = w21[4];
  w37 = w21[5];
  /* #62: @21 = vertcat(@6, @30, @34, @35, @36, @37, @23, @23) */
  rr=w21;
  *rr++ = w6;
  *rr++ = w30;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w36;
  *rr++ = w37;
  /* #63: {@6, @34, @38, @39, @40, @41} = vertsplit(@22) */
  w6 = w22[0];
  w34 = w22[1];
  w38 = w22[2];
  w39 = w22[3];
  w40 = w22[4];
  w41 = w22[5];
  /* #64: @22 = vertcat(@6, @34, @38, @39, @40, @41, @23, @23) */
  rr=w22;
  *rr++ = w6;
  *rr++ = w34;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #65: @18 = horzcat(@28, @17, @19, @20, @21, @22) */
  rr=w18;
  for (i=0, cs=w28; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<6; ++i) *rr++ = *cs++;
  /* #66: @25 = mac(@27,@18,@25) */
  casadi_mtimes(w27, casadi_s3, w18, casadi_s2, w25, casadi_s1, w, 0);
  /* #67: {@16, @42, @43, @44, @45, @46} = horzsplit(@25) */
  casadi_copy(w25, 3, w16);
  casadi_copy(w25+3, 3, w42);
  casadi_copy(w25+6, 3, w43);
  casadi_copy(w25+9, 3, w44);
  casadi_copy(w25+12, 3, w45);
  casadi_copy(w25+15, 3, w46);
  /* #68: @6 = @16[0] */
  for (rr=(&w6), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #69: @38 = @16[1] */
  for (rr=(&w38), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #70: @47 = @16[2] */
  for (rr=(&w47), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #71: @16 = vertcat(@23, @6, @23, @38, @23, @47) */
  rr=w16;
  *rr++ = w6;
  *rr++ = w38;
  *rr++ = w47;
  /* #72: @28 = dense(@16) */
  casadi_densify(w16, casadi_s4, w28, 0);
  /* #73: @14 = (@14+@28) */
  for (i=0, rr=w14, cs=w28; i<6; ++i) (*rr++) += (*cs++);
  /* #74: output[1][0] = @14 */
  casadi_copy(w14, 6, res[1]);
  /* #75: @6 = (@9*@8) */
  w6  = (w9*w8);
  /* #76: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #77: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #78: @8 = (@2*@8) */
  w8  = (w2*w8);
  /* #79: @8 = (@5*@8) */
  w8  = (w5*w8);
  /* #80: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #81: @8 = (-@8) */
  w8 = (- w8 );
  /* #82: @24 = vertcat(@10, @6, @12, @8, @1, @23) */
  rr=w24;
  *rr++ = w10;
  *rr++ = w6;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w1;
  /* #83: @14 = dense(@24) */
  casadi_densify(w24, casadi_s0, w14, 0);
  /* #84: @10 = @42[0] */
  for (rr=(&w10), ss=w42+0; ss!=w42+1; ss+=1) *rr++ = *ss;
  /* #85: @6 = @42[1] */
  for (rr=(&w6), ss=w42+1; ss!=w42+2; ss+=1) *rr++ = *ss;
  /* #86: @12 = @42[2] */
  for (rr=(&w12), ss=w42+2; ss!=w42+3; ss+=1) *rr++ = *ss;
  /* #87: @42 = vertcat(@23, @10, @23, @6, @23, @12) */
  rr=w42;
  *rr++ = w10;
  *rr++ = w6;
  *rr++ = w12;
  /* #88: @28 = dense(@42) */
  casadi_densify(w42, casadi_s4, w28, 0);
  /* #89: @14 = (@14+@28) */
  for (i=0, rr=w14, cs=w28; i<6; ++i) (*rr++) += (*cs++);
  /* #90: output[1][1] = @14 */
  if (res[1]) casadi_copy(w14, 6, res[1]+6);
  /* #91: @10 = (@9*@13) */
  w10  = (w9*w13);
  /* #92: @10 = (@5*@10) */
  w10  = (w5*w10);
  /* #93: @10 = (@7*@10) */
  w10  = (w7*w10);
  /* #94: @13 = (@2*@13) */
  w13  = (w2*w13);
  /* #95: @13 = (@5*@13) */
  w13  = (w5*w13);
  /* #96: @13 = (@7*@13) */
  w13  = (w7*w13);
  /* #97: @13 = (-@13) */
  w13 = (- w13 );
  /* #98: @24 = vertcat(@0, @10, @4, @13, @29, @23) */
  rr=w24;
  *rr++ = w0;
  *rr++ = w10;
  *rr++ = w4;
  *rr++ = w13;
  *rr++ = w29;
  /* #99: @14 = dense(@24) */
  casadi_densify(w24, casadi_s0, w14, 0);
  /* #100: @0 = @43[0] */
  for (rr=(&w0), ss=w43+0; ss!=w43+1; ss+=1) *rr++ = *ss;
  /* #101: @10 = @43[1] */
  for (rr=(&w10), ss=w43+1; ss!=w43+2; ss+=1) *rr++ = *ss;
  /* #102: @4 = @43[2] */
  for (rr=(&w4), ss=w43+2; ss!=w43+3; ss+=1) *rr++ = *ss;
  /* #103: @43 = vertcat(@23, @0, @23, @10, @23, @4) */
  rr=w43;
  *rr++ = w0;
  *rr++ = w10;
  *rr++ = w4;
  /* #104: @28 = dense(@43) */
  casadi_densify(w43, casadi_s4, w28, 0);
  /* #105: @14 = (@14+@28) */
  for (i=0, rr=w14, cs=w28; i<6; ++i) (*rr++) += (*cs++);
  /* #106: output[1][2] = @14 */
  if (res[1]) casadi_copy(w14, 6, res[1]+12);
  /* #107: @0 = (@9*@32) */
  w0  = (w9*w32);
  /* #108: @0 = (@5*@0) */
  w0  = (w5*w0);
  /* #109: @0 = (@7*@0) */
  w0  = (w7*w0);
  /* #110: @32 = (@2*@32) */
  w32  = (w2*w32);
  /* #111: @32 = (@5*@32) */
  w32  = (w5*w32);
  /* #112: @32 = (@7*@32) */
  w32  = (w7*w32);
  /* #113: @32 = (-@32) */
  w32 = (- w32 );
  /* #114: @24 = vertcat(@3, @0, @31, @32, @33, @23) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w0;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  /* #115: @14 = dense(@24) */
  casadi_densify(w24, casadi_s0, w14, 0);
  /* #116: @3 = @44[0] */
  for (rr=(&w3), ss=w44+0; ss!=w44+1; ss+=1) *rr++ = *ss;
  /* #117: @0 = @44[1] */
  for (rr=(&w0), ss=w44+1; ss!=w44+2; ss+=1) *rr++ = *ss;
  /* #118: @31 = @44[2] */
  for (rr=(&w31), ss=w44+2; ss!=w44+3; ss+=1) *rr++ = *ss;
  /* #119: @44 = vertcat(@23, @3, @23, @0, @23, @31) */
  rr=w44;
  *rr++ = w3;
  *rr++ = w0;
  *rr++ = w31;
  /* #120: @28 = dense(@44) */
  casadi_densify(w44, casadi_s4, w28, 0);
  /* #121: @14 = (@14+@28) */
  for (i=0, rr=w14, cs=w28; i<6; ++i) (*rr++) += (*cs++);
  /* #122: output[1][3] = @14 */
  if (res[1]) casadi_copy(w14, 6, res[1]+18);
  /* #123: @3 = (@9*@36) */
  w3  = (w9*w36);
  /* #124: @3 = (@5*@3) */
  w3  = (w5*w3);
  /* #125: @3 = (@7*@3) */
  w3  = (w7*w3);
  /* #126: @36 = (@2*@36) */
  w36  = (w2*w36);
  /* #127: @36 = (@5*@36) */
  w36  = (w5*w36);
  /* #128: @36 = (@7*@36) */
  w36  = (w7*w36);
  /* #129: @36 = (-@36) */
  w36 = (- w36 );
  /* #130: @24 = vertcat(@30, @3, @35, @36, @37, @23) */
  rr=w24;
  *rr++ = w30;
  *rr++ = w3;
  *rr++ = w35;
  *rr++ = w36;
  *rr++ = w37;
  /* #131: @14 = dense(@24) */
  casadi_densify(w24, casadi_s0, w14, 0);
  /* #132: @30 = @45[0] */
  for (rr=(&w30), ss=w45+0; ss!=w45+1; ss+=1) *rr++ = *ss;
  /* #133: @3 = @45[1] */
  for (rr=(&w3), ss=w45+1; ss!=w45+2; ss+=1) *rr++ = *ss;
  /* #134: @35 = @45[2] */
  for (rr=(&w35), ss=w45+2; ss!=w45+3; ss+=1) *rr++ = *ss;
  /* #135: @45 = vertcat(@23, @30, @23, @3, @23, @35) */
  rr=w45;
  *rr++ = w30;
  *rr++ = w3;
  *rr++ = w35;
  /* #136: @28 = dense(@45) */
  casadi_densify(w45, casadi_s4, w28, 0);
  /* #137: @14 = (@14+@28) */
  for (i=0, rr=w14, cs=w28; i<6; ++i) (*rr++) += (*cs++);
  /* #138: output[1][4] = @14 */
  if (res[1]) casadi_copy(w14, 6, res[1]+24);
  /* #139: @30 = (@9*@40) */
  w30  = (w9*w40);
  /* #140: @30 = (@5*@30) */
  w30  = (w5*w30);
  /* #141: @30 = (@7*@30) */
  w30  = (w7*w30);
  /* #142: @40 = (@2*@40) */
  w40  = (w2*w40);
  /* #143: @40 = (@5*@40) */
  w40  = (w5*w40);
  /* #144: @40 = (@7*@40) */
  w40  = (w7*w40);
  /* #145: @40 = (-@40) */
  w40 = (- w40 );
  /* #146: @24 = vertcat(@34, @30, @39, @40, @41, @23) */
  rr=w24;
  *rr++ = w34;
  *rr++ = w30;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #147: @14 = dense(@24) */
  casadi_densify(w24, casadi_s0, w14, 0);
  /* #148: @34 = @46[0] */
  for (rr=(&w34), ss=w46+0; ss!=w46+1; ss+=1) *rr++ = *ss;
  /* #149: @30 = @46[1] */
  for (rr=(&w30), ss=w46+1; ss!=w46+2; ss+=1) *rr++ = *ss;
  /* #150: @39 = @46[2] */
  for (rr=(&w39), ss=w46+2; ss!=w46+3; ss+=1) *rr++ = *ss;
  /* #151: @46 = vertcat(@23, @34, @23, @30, @23, @39) */
  rr=w46;
  *rr++ = w34;
  *rr++ = w30;
  *rr++ = w39;
  /* #152: @28 = dense(@46) */
  casadi_densify(w46, casadi_s4, w28, 0);
  /* #153: @14 = (@14+@28) */
  for (i=0, rr=w14, cs=w28; i<6; ++i) (*rr++) += (*cs++);
  /* #154: output[1][5] = @14 */
  if (res[1]) casadi_copy(w14, 6, res[1]+30);
  /* #155: @14 = zeros(2x6,6nz) */
  casadi_clear(w14, 6);
  /* #156: @34 = ones(2x1,1nz) */
  w34 = 1.;
  /* #157: {@30, NULL} = vertsplit(@34) */
  w30 = w34;
  /* #158: @34 = (@2*@30) */
  w34  = (w2*w30);
  /* #159: @34 = (@7*@34) */
  w34  = (w7*w34);
  /* #160: @39 = (@9*@30) */
  w39  = (w9*w30);
  /* #161: @39 = (@7*@39) */
  w39  = (w7*w39);
  /* #162: @40 = 0.707107 */
  w40 = 7.0710678118654746e-01;
  /* #163: @41 = 89285.7 */
  w41 = 8.9285714285714275e+04;
  /* #164: @3 = (@11*@30) */
  w3  = (w11*w30);
  /* #165: @3 = (@41*@3) */
  w3  = (w41*w3);
  /* #166: @3 = (@40*@3) */
  w3  = (w40*w3);
  /* #167: @3 = (-@3) */
  w3 = (- w3 );
  /* #168: @46 = vertcat(@23, @34, @23, @39, @23, @3) */
  rr=w46;
  *rr++ = w34;
  *rr++ = w39;
  *rr++ = w3;
  /* #169: @28 = zeros(3x2) */
  casadi_clear(w28, 6);
  /* #170: @34 = vertcat(@23, @23, @23, @23, @23, @23, @30, @23) */
  rr=(&w34);
  *rr++ = w30;
  /* #171: @30 = ones(2x1,1nz) */
  w30 = 1.;
  /* #172: {NULL, @39} = vertsplit(@30) */
  w39 = w30;
  /* #173: @30 = vertcat(@23, @23, @23, @23, @23, @23, @23, @39) */
  rr=(&w30);
  *rr++ = w39;
  /* #174: @48 = horzcat(@34, @30) */
  rr=w48;
  *rr++ = w34;
  *rr++ = w30;
  /* #175: @17 = mac(@27,@48,@28) */
  casadi_copy(w28, 6, w17);
  casadi_mtimes(w27, casadi_s3, w48, casadi_s6, w17, casadi_s5, w, 0);
  /* #176: {@45, @44} = horzsplit(@17) */
  casadi_copy(w17, 3, w45);
  casadi_copy(w17+3, 3, w44);
  /* #177: @34 = @45[0] */
  for (rr=(&w34), ss=w45+0; ss!=w45+1; ss+=1) *rr++ = *ss;
  /* #178: @30 = @45[1] */
  for (rr=(&w30), ss=w45+1; ss!=w45+2; ss+=1) *rr++ = *ss;
  /* #179: @3 = @45[2] */
  for (rr=(&w3), ss=w45+2; ss!=w45+3; ss+=1) *rr++ = *ss;
  /* #180: @45 = vertcat(@23, @34, @23, @30, @23, @3) */
  rr=w45;
  *rr++ = w34;
  *rr++ = w30;
  *rr++ = w3;
  /* #181: @46 = (@46+@45) */
  for (i=0, rr=w46, cs=w45; i<3; ++i) (*rr++) += (*cs++);
  /* #182: @45 = @46[:3] */
  for (rr=w45, ss=w46+0; ss!=w46+3; ss+=1) *rr++ = *ss;
  /* #183: (@14[:6:2] = @45) */
  for (rr=w14+0, ss=w45; rr!=w14+6; rr+=2) *rr = *ss++;
  /* #184: @34 = (@2*@39) */
  w34  = (w2*w39);
  /* #185: @34 = (@7*@34) */
  w34  = (w7*w34);
  /* #186: @30 = (@9*@39) */
  w30  = (w9*w39);
  /* #187: @30 = (@7*@30) */
  w30  = (w7*w30);
  /* #188: @11 = (@11*@39) */
  w11 *= w39;
  /* #189: @41 = (@41*@11) */
  w41 *= w11;
  /* #190: @40 = (@40*@41) */
  w40 *= w41;
  /* #191: @45 = vertcat(@23, @34, @23, @30, @23, @40) */
  rr=w45;
  *rr++ = w34;
  *rr++ = w30;
  *rr++ = w40;
  /* #192: @34 = @44[0] */
  for (rr=(&w34), ss=w44+0; ss!=w44+1; ss+=1) *rr++ = *ss;
  /* #193: @30 = @44[1] */
  for (rr=(&w30), ss=w44+1; ss!=w44+2; ss+=1) *rr++ = *ss;
  /* #194: @40 = @44[2] */
  for (rr=(&w40), ss=w44+2; ss!=w44+3; ss+=1) *rr++ = *ss;
  /* #195: @44 = vertcat(@23, @34, @23, @30, @23, @40) */
  rr=w44;
  *rr++ = w34;
  *rr++ = w30;
  *rr++ = w40;
  /* #196: @45 = (@45+@44) */
  for (i=0, rr=w45, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #197: @44 = @45[:3] */
  for (rr=w44, ss=w45+0; ss!=w45+3; ss+=1) *rr++ = *ss;
  /* #198: (@14[1:7:2] = @44) */
  for (rr=w14+1, ss=w44; rr!=w14+7; rr+=2) *rr = *ss++;
  /* #199: @17 = @14' */
  casadi_trans(w14,casadi_s8, w17, casadi_s7, iw);
  /* #200: @49 = dense(@17) */
  casadi_densify(w17, casadi_s7, w49, 0);
  /* #201: @50 = input[2][0] */
  casadi_copy(arg[2], 12, w50);
  /* #202: {@17, @14} = horzsplit(@50) */
  casadi_copy(w50, 6, w17);
  casadi_copy(w50+6, 6, w14);
  /* #203: {@34, @30, @40, @41, @11, @39} = vertsplit(@17) */
  w34 = w17[0];
  w30 = w17[1];
  w40 = w17[2];
  w41 = w17[3];
  w11 = w17[4];
  w39 = w17[5];
  /* #204: @3 = (@9*@11) */
  w3  = (w9*w11);
  /* #205: @3 = (@5*@3) */
  w3  = (w5*w3);
  /* #206: @3 = (@7*@3) */
  w3  = (w7*w3);
  /* #207: @35 = (@2*@11) */
  w35  = (w2*w11);
  /* #208: @35 = (@5*@35) */
  w35  = (w5*w35);
  /* #209: @35 = (@7*@35) */
  w35  = (w7*w35);
  /* #210: @35 = (-@35) */
  w35 = (- w35 );
  /* #211: @24 = vertcat(@30, @3, @41, @35, @39, @23) */
  rr=w24;
  *rr++ = w30;
  *rr++ = w3;
  *rr++ = w41;
  *rr++ = w35;
  *rr++ = w39;
  /* #212: @17 = dense(@24) */
  casadi_densify(w24, casadi_s0, w17, 0);
  /* #213: @19 = vertcat(@34, @30, @40, @41, @11, @39, @23, @23) */
  rr=w19;
  *rr++ = w34;
  *rr++ = w30;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w11;
  *rr++ = w39;
  /* #214: {@34, @30, @40, @41, @11, @39} = vertsplit(@14) */
  w34 = w14[0];
  w30 = w14[1];
  w40 = w14[2];
  w41 = w14[3];
  w11 = w14[4];
  w39 = w14[5];
  /* #215: @14 = vertcat(@34, @30, @40, @41, @11, @39, @23, @23) */
  rr=w14;
  *rr++ = w34;
  *rr++ = w30;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w11;
  *rr++ = w39;
  /* #216: @50 = horzcat(@19, @14) */
  rr=w50;
  for (i=0, cs=w19; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<6; ++i) *rr++ = *cs++;
  /* #217: @28 = mac(@27,@50,@28) */
  casadi_mtimes(w27, casadi_s3, w50, casadi_s9, w28, casadi_s5, w, 0);
  /* #218: {@44, @45} = horzsplit(@28) */
  casadi_copy(w28, 3, w44);
  casadi_copy(w28+3, 3, w45);
  /* #219: @34 = @44[0] */
  for (rr=(&w34), ss=w44+0; ss!=w44+1; ss+=1) *rr++ = *ss;
  /* #220: @40 = @44[1] */
  for (rr=(&w40), ss=w44+1; ss!=w44+2; ss+=1) *rr++ = *ss;
  /* #221: @3 = @44[2] */
  for (rr=(&w3), ss=w44+2; ss!=w44+3; ss+=1) *rr++ = *ss;
  /* #222: @44 = vertcat(@23, @34, @23, @40, @23, @3) */
  rr=w44;
  *rr++ = w34;
  *rr++ = w40;
  *rr++ = w3;
  /* #223: @28 = dense(@44) */
  casadi_densify(w44, casadi_s4, w28, 0);
  /* #224: @17 = (@17+@28) */
  for (i=0, rr=w17, cs=w28; i<6; ++i) (*rr++) += (*cs++);
  /* #225: @9 = (@9*@11) */
  w9 *= w11;
  /* #226: @9 = (@5*@9) */
  w9  = (w5*w9);
  /* #227: @9 = (@7*@9) */
  w9  = (w7*w9);
  /* #228: @2 = (@2*@11) */
  w2 *= w11;
  /* #229: @5 = (@5*@2) */
  w5 *= w2;
  /* #230: @7 = (@7*@5) */
  w7 *= w5;
  /* #231: @7 = (-@7) */
  w7 = (- w7 );
  /* #232: @24 = vertcat(@30, @9, @41, @7, @39, @23) */
  rr=w24;
  *rr++ = w30;
  *rr++ = w9;
  *rr++ = w41;
  *rr++ = w7;
  *rr++ = w39;
  /* #233: @28 = dense(@24) */
  casadi_densify(w24, casadi_s0, w28, 0);
  /* #234: @30 = @45[0] */
  for (rr=(&w30), ss=w45+0; ss!=w45+1; ss+=1) *rr++ = *ss;
  /* #235: @9 = @45[1] */
  for (rr=(&w9), ss=w45+1; ss!=w45+2; ss+=1) *rr++ = *ss;
  /* #236: @41 = @45[2] */
  for (rr=(&w41), ss=w45+2; ss!=w45+3; ss+=1) *rr++ = *ss;
  /* #237: @45 = vertcat(@23, @30, @23, @9, @23, @41) */
  rr=w45;
  *rr++ = w30;
  *rr++ = w9;
  *rr++ = w41;
  /* #238: @19 = dense(@45) */
  casadi_densify(w45, casadi_s4, w19, 0);
  /* #239: @28 = (@28+@19) */
  for (i=0, rr=w28, cs=w19; i<6; ++i) (*rr++) += (*cs++);
  /* #240: @50 = horzcat(@17, @28) */
  rr=w50;
  for (i=0, cs=w17; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<6; ++i) *rr++ = *cs++;
  /* #241: @49 = (@49+@50) */
  for (i=0, rr=w49, cs=w50; i<12; ++i) (*rr++) += (*cs++);
  /* #242: output[2][0] = @49 */
  casadi_copy(w49, 12, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor2D_learned_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    case 3: return casadi_s13;
    case 4: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 208;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 208*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
