/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor2D_learned_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};

/* External functions */
int adj1_residual_quadrotor2D(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* adj1_residual_quadrotor2D:(i0[1x8],out_o0[1x3,0nz],adj_o0[1x3])->(adj_i0[1x8]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (adj1_residual_quadrotor2D(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* quadrotor2D_learned_expl_vde_adj:(i0[6],i1[6],i2[2],i3[0])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+8, *w10=w+16, *w11=w+19, w12, *w13=w+26, w14, w15, w16, w17, w18, w19, w20, w21;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = input[2][0] */
  w6 = arg[2] ? arg[2][0] : 0;
  /* #7: @7 = input[2][1] */
  w7 = arg[2] ? arg[2][1] : 0;
  /* #8: @8 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7) */
  rr=w8;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #9: @8 = @8' */
  /* #10: @9 = zeros(1x3,0nz) */
  /* #11: @10 = zeros(3x1) */
  casadi_clear(w10, 3);
  /* #12: @11 = input[1][0] */
  casadi_copy(arg[1], 6, w11);
  /* #13: {@0, @1, @2, @3, @5, @12} = vertsplit(@11) */
  w0 = w11[0];
  w1 = w11[1];
  w2 = w11[2];
  w3 = w11[3];
  w5 = w11[4];
  w12 = w11[5];
  /* #14: (@10[2] += @12) */
  for (rr=w10+2, ss=(&w12); rr!=w10+3; rr+=1) *rr += *ss++;
  /* #15: (@10[1] += @3) */
  for (rr=w10+1, ss=(&w3); rr!=w10+2; rr+=1) *rr += *ss++;
  /* #16: (@10[0] += @1) */
  for (rr=w10+0, ss=(&w1); rr!=w10+1; rr+=1) *rr += *ss++;
  /* #17: @10 = @10' */
  /* #18: @13 = adj1_residual_quadrotor2D(@8, @9, @10) */
  arg1[0]=w8;
  arg1[1]=0;
  arg1[2]=w10;
  res1[0]=w13;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #19: @13 = @13' */
  /* #20: {@14, @15, @16, @17, @18, @19, @20, @21} = vertsplit(@13) */
  w14 = w13[0];
  w15 = w13[1];
  w16 = w13[2];
  w17 = w13[3];
  w18 = w13[4];
  w19 = w13[5];
  w20 = w13[6];
  w21 = w13[7];
  /* #21: output[0][0] = @14 */
  if (res[0]) res[0][0] = w14;
  /* #22: @15 = (@15+@0) */
  w15 += w0;
  /* #23: output[0][1] = @15 */
  if (res[0]) res[0][1] = w15;
  /* #24: output[0][2] = @16 */
  if (res[0]) res[0][2] = w16;
  /* #25: @17 = (@17+@2) */
  w17 += w2;
  /* #26: output[0][3] = @17 */
  if (res[0]) res[0][3] = w17;
  /* #27: @17 = sin(@4) */
  w17 = sin( w4 );
  /* #28: @6 = (@6+@7) */
  w6 += w7;
  /* #29: @7 = 56.1167 */
  w7 = 5.6116722783389456e+01;
  /* #30: @3 = (@7*@3) */
  w3  = (w7*w3);
  /* #31: @2 = (@6*@3) */
  w2  = (w6*w3);
  /* #32: @2 = (@17*@2) */
  w2  = (w17*w2);
  /* #33: @18 = (@18-@2) */
  w18 -= w2;
  /* #34: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #35: @7 = (@7*@1) */
  w7 *= w1;
  /* #36: @6 = (@6*@7) */
  w6 *= w7;
  /* #37: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #38: @18 = (@18+@6) */
  w18 += w6;
  /* #39: output[0][4] = @18 */
  if (res[0]) res[0][4] = w18;
  /* #40: @19 = (@19+@5) */
  w19 += w5;
  /* #41: output[0][5] = @19 */
  if (res[0]) res[0][5] = w19;
  /* #42: @19 = 0.0397 */
  w19 = 3.9699999999999999e-02;
  /* #43: @5 = 89285.7 */
  w5 = 8.9285714285714275e+04;
  /* #44: @18 = 0.707107 */
  w18 = 7.0710678118654746e-01;
  /* #45: @18 = (@18*@12) */
  w18 *= w12;
  /* #46: @5 = (@5*@18) */
  w5 *= w18;
  /* #47: @19 = (@19*@5) */
  w19 *= w5;
  /* #48: @20 = (@20-@19) */
  w20 -= w19;
  /* #49: @4 = (@4*@3) */
  w4 *= w3;
  /* #50: @20 = (@20+@4) */
  w20 += w4;
  /* #51: @17 = (@17*@7) */
  w17 *= w7;
  /* #52: @20 = (@20+@17) */
  w20 += w17;
  /* #53: output[0][6] = @20 */
  if (res[0]) res[0][6] = w20;
  /* #54: @21 = (@21+@19) */
  w21 += w19;
  /* #55: @21 = (@21+@4) */
  w21 += w4;
  /* #56: @21 = (@21+@17) */
  w21 += w17;
  /* #57: output[0][7] = @21 */
  if (res[0]) res[0][7] = w21;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor2D_learned_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 42;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 42*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
